### ISSUE TITLE
Permissions denied

### ISSUE THREAD

**Issue by Alkaris** [rust-lang-nursery/rustup.rs#1321]
Trying to install Rustup bash completions but it's just giving me permissions denied, I tried running with sudo, but still permissions denied

as it instructs it says to do;

`rustup completions bash > /etc/bash_completion.d/rustup.bash-completion`

but this doesn't work, and instead returns permission denied. I have tried changing permissions for `/etc/bash_completion.d` but that still doesn't work. You shouldn't be having to use root to install this.

**Comment by sbrl** [comment]
Sounds like you need to do `rustup completions bash | sudo tee /etc/bash_completion.d/rustup.bash-completion`.

This is because the pipe (`>`) is still executed as the local user - not root. Using `sudo tee` forces it to do the piping to disk as root.
