### ISSUE TITLE
Add feature to set the default host, distribute only a single windows binary

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#137]
To make the installation simple, and possibly to solve the issue of needing VC dlls, I think we should have all windows users install the same binary (probably i686-pc-windows-gnu?). We'll pick the smartest host by default, so even though we're distributing i686-pc-windows-gnu binaries rustup might default to x86_64-pc-windows-msvc.

To use a different host it may be sufficient to just use the existing support and specify `msvc` or `gnu` in all the toolchain names. If not we can add a way to set the default host.

This will require normalizing toolchain names.

**Comment by Diggsey** [comment]
#421 !

**Comment by brson** [comment]
Thanks @Diggsey.
