### ISSUE TITLE
rust-lldb not available on Linux

### ISSUE THREAD

**Issue by Luthaf** [rust-lang-nursery/rustup.rs#144]
Trying to run `rust-lldb` gives me the `error: infinite recursion detected: the command may not exist for this toolchain` error.

`rust-llbd` is effectively missing in `.multirust/toolchains/stable/bin` but it could be installed there, as lldb is available on Linux. (I got mine from the epel repo, but some people can also have it installed from sources).

Is it an issue for multirust or for the main rust repo ?

**Comment by brson** [comment]
This could have a better error than just blindly recursing. I don't intend to remove the proxy binary and think Rust should distribute rust-gdb and rust-lldb unconditionally.

**Comment by Luthaf** [comment]
> think Rust should distribute rust-gdb and rust-lldb unconditionally.

I am in favour of that too.

**Comment by Luthaf** [comment]
Dup of #335
