### ISSUE TITLE
Consider `rustup install`

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#151]
`rustup update` both updates and installs, but 'update' is an unintuitive word for the initial install. It may be worth having `install` be a synonym for `update`, or possibly just renaming `update` to `install`.

**Comment by chriskrycho** [comment]
If/when you and the team come to a decision about the best way to approach this, let me know; I'd be happy to help ship some of the code for it.

**Comment by brson** [comment]
Thanks @chriskrycho. I intend to ask for beta testing soon, and this is one of the questions I'd like to pose to people. We'll see how others feel about it. My main reservation right now is having a duplicate subcommand.

**Comment by Gyscos** [comment]
Many package managers use the same work for installation and update.
`pacman` (on Archlinux) uses `sync`, which is a bit more neutral than the more common `install` (from `dpkg` for instance).

**Comment by Flaise** [comment]
`npm` uses `install`. I don't think it's awkward; on Windows and Mac OS X we "install updates", the verb therefore being "install".
