### ISSUE TITLE
.multirust has moved back to home directory

### ISSUE THREAD

**Issue by Diggsey** [rust-lang-nursery/rustup.rs#158]
The .multirust directory was moved to %localappdata% on windows, to follow platform conventions, and to avoid cluttering the home directory, but it has since been moved back.

I think there was also a plan to unify the .multirust and .cargo directories too?

**Comment by brson** [comment]
For consistency with where `.cargo` lives, `.multirust` is now in `%USERPROFILE%\.multirust`. If we want to change conventions here it needs to be done in both cargo and rustup.

There's no plan to unify `.multirust` and `.cargo` exactly. `~/.cargo/bin` is where the rustup bins are installed - for consistency with other rust bins - but other than that rustup doesn't care about `~/.cargo.

**Comment by Diggsey** [comment]
OK, this should be tied to rust-lang/cargo#1976 then.
