### ISSUE TITLE
Allow the user to tell rustup-setup which toolchain to install initially

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang-nursery/rustup.rs#218]
Right now when you run `rustup-setup` on a fresh machine, it automatically installs the stable toolchain. If the user knows they are not going to be using stable, this is a waste of time and bandwidth. `rustup-setup` should take some sort of option to tell it which toolchain to install.

**Comment by brson** [comment]
Probably `--default-toolchain`. `rustup-setup.sh` needs to also be modified to pass arguments through.

Related to https://github.com/rust-lang-nursery/multirust-rs/issues/170

**Comment by jimmycuadra** [comment]
#245 resolved this. Thanks!
