### ISSUE TITLE
Build openssl on appveyor

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#243]
The way we are acquiring openssl in our windows builds is sub-optimal. Can we build this ourselves like on linux?

cc @alexcrichton 

In the long term, switching from hyper to curl and rust-crypto (for sha256) is probably best because that gets is HTTP proxy support (what that entails I'm not sure), but we need to tighten this up.

**Comment by alexcrichton** [comment]
Oh oops I meant to comment on this earlier.

I personally have no idea how to compile OpenSSL on Windows, but I would probably personally still advocate for switching to curl temporarily for proxy support.
