### ISSUE TITLE
Rename rustup-setup to rustup-init

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#255]
The name `setup` has special meaning on Windows. It expects `setup` to be a windowsy setup program, doing specific things that rustup does not do. Let's avoid the whole problem by renaming the installer yet again to `rustup-init`. Anybody else have better names?

cc @vadimcn @retep998 what do you think?

**Comment by retep998** [comment]
Alternatively we could make it an actual installer.

**Comment by brson** [comment]
@retep998 That's the subject of https://github.com/rust-lang-nursery/multirust-rs/issues/253

**Comment by taralx** [comment]
Alternatively you could embed a manifest.
