### ISSUE TITLE
Broken link to sha256 hash breaks the install

### ISSUE THREAD

**Issue by plumenator** [rust-lang-nursery/rustup.rs#260]
The broken link https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256 which is used by the installer is missing. This breaks the install instructions given at https://www.rustup.rs

**Comment by brson** [comment]
Thanks for the report. Can you expand on how it breaks the install? Does installation of rustup fail, or is stable not installed?

This file will be published for the 1.8 release, but in the meantime installation should still work. The main thing that should not work on stable right now is `rustup target`.

**Comment by plumenator** [comment]
The install script waits on URL until times out and exits abruptly. It creates the .multirust, .cargo directories, copies rustup, etc. but stable doesn't get installed. 

The official installer on the other hand, ignores the missing link and skips the signature verification.

**Comment by brson** [comment]
@plumenator Can you post a log of running `rustup-setup -y --verbose`? What platform are you on?

There shouldn't be any timeout involved. That file just doesn't exist and should immediately return 404.

**Comment by plumenator** [comment]
Here you go:
```
$ uname -a
Linux xxxxxxxxxxxxxxxxxxxxx 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core
$ ~/Downloads/rustup-setup -y --verbose
verbose: installing toolchain 'stable'
verbose: toolchain directory: '/home/plumenator/.multirust/toolchains/stable'
info: syncing channel updates for 'stable'
verbose: creating temp file: /home/plumenator/.multirust/tmp/1d5jsb4rtnk44qho_file
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'
.
.
.
# Blocks here for a *very* long time (586.280202 seconds)
.
.
.
verbose: deleted temp file: /home/plumenator/.multirust/tmp/1d5jsb4rtnk44qho_file
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to '/home/plumenator/.multirust/tmp/1d5jsb4rtnk44qho_file' (Network: other os error)
```

**Comment by brson** [comment]
Thanks a lot!
