### ISSUE TITLE
Provide link to other install methods on the default website

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#269]
If it can't detect the platform it should provide links to the other downloads in the readme. Soon we're going to have a variety of low-tier platforms where we're less likely to guess correctly.

**Comment by nodakai** [comment]
```html
<p id="about">
  <a href="https://github.com/rust-lang-nursery/multirust-rs/blob/master/README.md">More about rustup</a>.
</p>
```

This is too terse to the level that it looks like a useless cliche on a website. Compare it with a wording by the Python team:

- https://www.python.org/downloads/

> Looking for Python with a different OS? Python for Windows, Linux/UNIX, Mac OS X, Other
