### ISSUE TITLE
Make error handling more robust, add more test cases

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#273]
The way error handling is set up right now makes it difficult to write new code, and tempting to discard intermediate errors. This is mostly due to a lack of automatic `From` conversions between error types, so every time you encounter a new error type you have to go create a new custom error to wrap it. Cargo has a robust error library that handles inner errors well. Let's just copy that.

Think through common error scenarios and add test cases.

**Comment by Diggsey** [comment]
I think this was solved by error_chain?
