### ISSUE TITLE
"rustup toolchain list" doesn't indicate the default toolchain

### ISSUE THREAD

**Issue by TheRealBluebird** [rust-lang-nursery/rustup.rs#286]
If I forget which toolchain is the default, the simplest way to find out appears to be "rustc -V" (and to then know that 1.7 is "stable", etc.) but an asterisk beside the default entry in the output of "rustup toolchain list" would make more sense.

**Comment by JIghtuse** [comment]
@TheRealBluebird there is `rustup show`, which displays the active toolchain. Anyway, including asterisk would be a nice tiny change.

**Comment by brson** [comment]
This is indicated with "(default)" now.
