### ISSUE TITLE
MSVC 32 bit & Mingw 64 bit rustup-init.exe 0.1.12 aborts even with -V

### ISSUE THREAD

**Issue by nodakai** [rust-lang-nursery/rustup.rs#295]
This is a major step backwards

**Comment by nodakai** [comment]
It appears that only 32 bit rustup-setup.exes causes this issue on my Windows machine.

$ sha1sum rustup-setup*.exe
c5334c46884d7adc8bc6bada29a42d3c7a411c2d *rustup-setup-g32.exe
8794eae5b91cc3bd3e1db7da97a9228be6576108 *rustup-setup-g64.exe
121c669822f3f7637d571a24d369d6f4ea78a4c5 *rustup-setup-v32.exe
d8dae8f44739f820cd1cee1b6184a350ddf343b4 *rustup-setup-v64.exe

**Comment by brson** [comment]
Hopefully it's the same issue as https://github.com/rust-lang-nursery/multirust-rs/issues/255

**Comment by nodakai** [comment]
![image](https://cloud.githubusercontent.com/assets/90726/14708698/15a5aa7e-07ff-11e6-9d37-66817a18c7cf.png)

$ sha256sum.exe rustup-init-v32.exe
3623a47dcf3dc98a1a089e046c38776418f71276dfdb12c25e7f8c2021ad0263 *rustup-init-v32.exe

**Comment by brson** [comment]
Terrible!

**Comment by Diggsey** [comment]
This has been fixed a long time.
