### ISSUE TITLE
Add the ability to configure whether components are installed

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#298]
Two use cases:
- It'd be nice to have the ability to either opt-out of rust-docs installation or opt-in to tracking it. I don't have much of a preference either way, but I personally at least don't use the component much so it'd be nice to download/copy less.
- For MinGW toolchains I have MSYS installed and get weird errors sometimes when the `rust-mingw` component is installed because C code is sometimes compiled with my MSYS toolchain and then linked with `rust-mingw`'s toolchain (causing errors).

**Comment by brson** [comment]
For rust-docs at least, we're just going to blanket convert it to an optional component, so it won't be installed by default.

Maybe `rust-mingw` should also be converted to an optional component until we figure out something better to do with it.

**Comment by brson** [comment]
Adding an ability to optionally install *required* components seems wrong.

**Comment by brson** [comment]
This issue can be for a general `rustup component` subcommand, which we'll need before rust-docs can become optional.

**Comment by alexcrichton** [comment]
I'm fine leaving `rust-mingw` installed-by-default for now, I was just thinking that there's some way to opt out of installing it (which is persisted)

**Comment by brson** [comment]
Maybe this speaks to a need for a new type of component, one that is not required but is installed by default. Though i'm still more inclined to relegate rust-mingw to the ndk layer.

**Comment by brson** [comment]
(Or maybe we just don't have to be so strict about what "required" means and just allow people to mix and match components in ways that break).

**Comment by Diggsey** [comment]
Superceded by #905
