### ISSUE TITLE
"target list" shows unavailable toolchains

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#299]
On stable, for example, we don't even try to produce NetBSD binaries, so in the manifests these are listed as unailable. The UI though doesn't indicate this so it looks like you can install NetBSD.

**Comment by andreastt** [comment]
I ran into the same problem this afternoon trying to add _i686-unknown-linux-musl_, which is only available on the beta- and nightly channels:

```% rustup target add --toolchain stable i686-unknown-linux-musl
error: component 'rust-std' for 'i686-unknown-linux-musl' is unavailable for download
```

**Comment by brson** [comment]
This is a fairly easy fix. Every component defined in the manifest has an 'available' flag that just needs to be surfaced further.

In `Toolchain::list_components` the returned `ComponentStatus` needs an `available` field, which it can fill in similarly to how `Manifestation` detects unavailable components. For each component in the manifest it needs to look up that component's package definition to find the `available` field. Once `ComponentStatus` has the field then `common::list_targets` can filter it out.

**Comment by brson** [comment]
Fixed. Thanks @Geemili
