### ISSUE TITLE
"target add" could take a list of targets

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#300]
Right now I execute `rustup target add` once per target, but it'd be kinda cool if I could do it all at once. That way a shell command like this would work by default:

```
rustup target add {i686,x86_64}-pc-windows-{gnu,mvsc}
```

**Comment by brson** [comment]
It's probably trivial to have clap match multiple arguments here. sgtm

**Comment by Diggsey** [comment]
This is implemented afaik
