### ISSUE TITLE
toolchain remove fails when update-hash does not exist

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#304]
If the update hash doesn't exist for a toolchain then `toolchain remove` returns an error:

```
PS C:\Users\Jonas\Documents\breeze-emu> rustup toolchain remove nightly-i686-pc-windows-msvc
info: uninstalling toolchain 'nightly-i686-pc-windows-msvc'
error: could not remove update hash file: 'C:\Users\Jonas\.multirust\update-hashes\nightly-i686-pc-windows-msvc' (Das System kann die angegebene Datei nicht finden. (os error 2))
PS C:\Users\Jonas\Documents\breeze-emu>
```

In this case the metadata was in an inconsistent state after a failed `toolchain remove`.

If the file doesn't exist then the error should silently be ignored.

[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/80?u=brson).

**Comment by exscape** [comment]
Hmm, I just hit this over a year later.
In cygwin:

    ~ $ rustup toolchain uninstall nightly
    info: uninstalling toolchain 'nightly-x86_64-pc-windows-gnu'
    error: could not remove 'install' directory: 'C:\Users\serenity\.rustup\toolchains\nightly-x86_64-pc-windows-gnu'
    info: caused by: Access is denied. (os error 5)

So I figured I'd try again in a Windows admin cmd shell:

    C:\>rustup toolchain uninstall nightly
    info: uninstalling toolchain 'nightly-x86_64-pc-windows-gnu'
    error: could not remove 'update hash' file: 'C:\Users\serenity\.rustup\update-hashes\nightly-x86_64-pc-windows-gnu'
    info: caused by: The system cannot find the file specified. (os error 2)

**Comment by Moraxes** [comment]
I also ran into this. Worked around it by creating an empty file at that path. Although since its contents are evidently ignored (at least at `toolchain remove` time), it being missing should probably be ignored (or just don't remove it on a failed `toolchain remove`, I guess).

**Comment by jnm2** [comment]
Same thing. :-(

**Comment by nox** [comment]
This just busted a buildbot machine in Servo's CI. Quite unfortunate.

**Comment by ghost** [comment]
This issue can be closed now. 
It didn't close when the fix was committed because I messed up the commit message.

**Comment by CAD97** [comment]
I just ran into this issue.

```
C:\Users\cad97>rustup toolchain uninstall beta-msvc
info: uninstalling toolchain 'beta-x86_64-pc-windows-msvc'
error: could not remove 'install' directory: 'D:\usr\.rustup\toolchains\beta-x86_64-pc-windows-msvc'
info: caused by: Access is denied. (os error 5)

# NOTE: RLS was running on beta-msvc in a different window; restarted RLS on beta-gnu here

C:\Users\cad97>rustup toolchain uninstall beta-msvc
info: uninstalling toolchain 'beta-x86_64-pc-windows-msvc'
error: could not remove 'update hash' file: 'D:\usr\.rustup\update-hashes\beta-x86_64-pc-windows-msvc'
info: caused by: The system cannot find the file specified. (os error 2)
```

**Comment by ghost** [comment]
What version of rustup did you use?

**Comment by CAD97** [comment]
```
C:\Users\cad97>rustup --version
rustup 1.13.0 (ea9259c1b 2018-07-16)
```

The latest, `rustup self update` doesn't install a newer version.
(But the date is before the fix; maybe a new version needs to be pushed?)
(I see 1.14 in the GitHub releases, but `rustup self update` does not update me to `rustup:1.14`.)
