### ISSUE TITLE
I cannot run rustup and other executables right after installation on Mac OSX.

### ISSUE THREAD

**Issue by piaoger** [rust-lang-nursery/rustup.rs#305]
I cannot run rustup and other executables right after installation on Mac OSX. I found below line is appended to ~/.bashrc, not ~/.bash_profile instead:
   export PATH="$HOME/.cargo/bin:$PATH"

**Comment by peschkaj** [comment]
Related to #211 (and somewhat related to #170 and #293).

**Comment by brson** [comment]
@piaoger rustup now sets `PATH` in `~/.profile` instead of `~/.bashrc`. Does that work for you?

**Comment by brson** [comment]
Oh, that change isn't published yet. I'll publish a new revision today.

**Comment by piaoger** [comment]
@brson

**Comment by brson** [comment]
Thanks for verifying @piaoger. Considering this fixed.
