### ISSUE TITLE
No info printed on `rustup target remove`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#306]
Right now a successful `rustup target remove` doesn't actually print anything, whereas most other commands print out something like "successfully did blah".

**Comment by brson** [comment]
Since `install` says:

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustup target add i686-unknown-linux-gnu
info: downloading component 'rust-std' for 'i686-unknown-linux-gnu'
info: installing component 'rust-std' for 'i686-unknown-linux-gnu'
```

Seems like an appropriate message is

```
info: removing component 'rust-std' for 'i686-unknown-linux-gnu'
```

Neither indicates that the command was finally _installed_ or _removed_, but saying "removing" is at least consistent with the existing logs, and it prints something.
