### ISSUE TITLE
armv7 build doesn't default to armv7 but to arm

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#308]
The `get_original_host_triple` function just uses `env::consts::ARCH` for the arch part of the target, but it should be `armv7`. Hopefully we can derive this info without setting `RUSTUP_OVERRIDE_HOST_TRIPLE`.

cc @japaric

**Comment by brson** [comment]
@japaric suggested using one of the many variables Cargo sets by default, one of which is probably `TARGET`.

**Comment by japaric** [comment]
It appears TARGET is only set for build scripts as [documented here](https://github.com/rust-lang/cargo/blob/master/src/doc/environment-variables.md). I'm not sure if we can use some `build.rs` magic to forward the variable to the `cargo build` process. @alexcrichton Know of any way to access TARGET during the compilation of a crate?

**Comment by alexcrichton** [comment]
a bit hackish but you can

* In a build script, emit `env::var("TARGET")` into a file.
* In a crate, include it via `include_str!`

**Comment by japaric** [comment]
@alexcrichton That's what I feared :P. I'll prepare a PR and let @brson decide.
