### ISSUE TITLE
Add `self default-host` command, make it configurable at install

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#309]
On Windows in particular, there are lots of architectures people may prefer to build for by default. Right now you have to either download a specific build of rustup to get a specific host compiler, or you have to explicitly install each toolchain for that architecture.

This behavior is too surprising and the solution too undiscoverable. I think the best thing to do is have a "default host" configuration and make it configurable at install time.

The commands for this might be `rustup self set-default-host` and `rustup self show-default-host`.

During installation, as part of the install message, we'll mention the host architecture and that it can be changed. We may only need to indicate this in the Windows install message, since that's where it matters most, not sure.

**Comment by brson** [comment]
`rustup-init` also needs a `--default-host` option.

**Comment by Diggsey** [comment]
Some related things that would be nice:

1) Look for `WOW64` or `Win64` in the User Agent string on `rustup.rs` when deciding which build architecture to use. (http://stackoverflow.com/questions/1741933/detect-64-bit-or-32-bit-windows-from-user-agent-or-javascript). This is an easy fix that will immediately improve things for most people encountering this problem.

This may seem redundant, but I'd prefer rustup itself to be 64-bit if I'm using it on a 64-bit OS.

2) Make some attempt to detect the host architecture on install. This means eg. checking if the host is 64-bit even if rustup itself is 32-bit, and similar for other platforms.

3) When installing interatively, ask the user to confirm or change the host architecture.

**Comment by brson** [comment]
> 2) Make some attempt to detect the host architecture on install. This means eg. checking if the host is 64-bit even if rustup itself is 32-bit, and similar for other platforms.

Yeah, good idea.

**Comment by brson** [comment]
After further pondering I prefer `rustup toolchain set-default-host` and `rustup toolchain show-default-host` since this affects toolchain selection.

**Comment by petrochenkov** [comment]
It would be useful to have an option to not install any toolchains.

Scenario: there's a server with several users and one common preinstalled Rust toolchain that is not in `PATH`.
A new user installs `rustup` and "connects" to that toolchain with `rustup toolchain link` without installing any toolchains for himself.

**Comment by brson** [comment]
@petrochenkov Agreed, yeah.

The case of installing `rustup` system-wide needs more attention generally. I think there's a strong case for distributing rustup through normal platform stores, not doing self-updates, etc.

**Comment by Diggsey** [comment]
This is implemented with #421
