### ISSUE TITLE
Cannot rustup self update on Windows

### ISSUE THREAD

**Issue by alexbool** [rust-lang-nursery/rustup.rs#315]
Looks like this:
```
$ rustup -V
rustup 0.1.4

$ rustup --verbose self update
verbose: read metadata version: '12'
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully
error: unable to run updater

$ rustup -V
rustup 0.1.4
```

I can provide any other info on your request.

**Comment by allentc** [comment]
Try the self update in a _runas_ Adminstrator cmd shell.  I see the same error and this solved it.

**Comment by alexbool** [comment]
Yep, running as Administrator helped.
This should be more clear though.

**Comment by allentc** [comment]
Indeed.  Perhaps a more helpful message [here](https://github.com/rust-lang-nursery/rustup.rs/blob/ec56e66ccfb6e5dee2e8c46797dbb71929a27fd9/src/rustup-cli/self_update.rs#L985).

**Comment by brson** [comment]
I am hopeful this will fix itself with the next update. The new updater is named `rustup-init` instead of `rustup-setup`. Windows treats "setup" exes specially.

**Comment by Diggsey** [comment]
The change to `rustup-init` has been made so I think this can be closed now.
