### ISSUE TITLE
`rustup override remove` does not work for windows root directories`

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#316]
If I'm in C:\

```
$ rustup override add nightly
$ rustup override remove
info: no override toolchain for 'C:\'
```

**Comment by pravic** [comment]
Not works with the root directory, as reported and confirmed.

**Comment by brson** [comment]
I was also able to reproduce the error you saw where `rustc` printed the wrong version for the "C:\" override.
