### ISSUE TITLE
rustup-setup panics on freebsd

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/rustup.rs#318]
When I try to install rustup with curl https://sh.rustup.rs -sSf | sh on my FreeBSD machine, I get the error thread '<main>' panicked at 'not yet implemented', src/multirust-dist/src/dist.rs:390.

---

originally reported [here](https://users.rust-lang.org/t/psa-rustc-cargo-can-now-be-installed-on-arm-linux-netbsd-and-freebsd-using-rustup-multirust/5383/9?u=japaric)

**Comment by brson** [comment]
This was probably related to the platform detection that you already fixed.

**Comment by japaric** [comment]
This was fixed in the last release.
