### ISSUE TITLE
Links broken for "Other Installation Methods"

### ISSUE THREAD

**Issue by futile** [rust-lang-nursery/rustup.rs#333]
The page under https://github.com/rust-lang-nursery/rustup.rs#other-installation-methods links to several `rustup-init` files for different platforms, but these links seem to be broken. I clicked a few random ones, including `x86_64-unknown-linux-gnu`, and always got a "Not Found" error page instead of the expected binary.

**Comment by nodakai** [comment]
Perhaps that was just a temporary CDN issue or something like that; now they are all fine except arm-unknown-linux-**gnueabi** for which I've just filed #348

**Comment by futile** [comment]
Yeah, they seem to be fine again, thanks @nodakai :)!
