### ISSUE TITLE
curl: (35) TCP connection reset by peer

### ISSUE THREAD

**Issue by andrewrynhard** [rust-lang-nursery/rustup.rs#336]
On linux (centos7) I get this error when running:
````
$ curl https://sh.rustup.rs -sSf | sh
curl: (35) TCP connection reset by peer
````

I can download the file with my browser, and I can curl other script installers just fine. I can also curl from OS X. Not sure if this info is helpful but that is the little bit of debugging I have done.

**Comment by andrewrynhard** [comment]
`curl https://sh.rustup.rs -sSf | sh` now works

**Comment by brson** [comment]
Weird. I don't think anything changed on this side.

One thing that causes compatibility problems with older curls is that our server rejects SSL3. I don't think that's what happened for you though.

**Comment by nodakai** [comment]
@andrewrynhard Next time you can try `curl -v ...`

**Comment by brson** [comment]
Without further evidence I don't think there's much we can do about this. Let me know if it happens again.

**Comment by omega-tree** [comment]
Getting similar issues.  same distro (centos 7).  Here is the verbose output.

sudo curl https://sh.rustup.rs -v | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to sh.rustup.rs port 443 (#0)
*   Trying 54.215.0.2...
* Connected to sh.rustup.rs (54.215.0.2) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
* Closing connection 0
curl: (35) TCP connection reset by peer

**Comment by bjk543** [comment]
same here

**Comment by francesco-cattoglio** [comment]
same here
NSS error -5961 (PR_CONNECT_RESET_ERROR)
got that error on a remote server running CentOS 7.0

The error went away by loading the server's curl module. It might have to do with outdated curl, perhaps.

**Comment by jiangchao1987** [comment]
same here

**Comment by nodakai** [comment]
How about...

```
while ! curl https://sh.rustup.rs -sSf; do sleep 3; done | sh
```

😭

**Comment by AmiRM4A** [comment]
Did u guys find any solutions?

I get the same error (Rec Failure - 35) while trying to `curl https://google.com`

Output of `curl -vvv https://google.com`:
```
* Host google.com:443 was resolved.
* IPv6: 2001:4860:4802:32::78
* IPv4: 216.239.38.120
*   Trying [2001:4860:4802:32::78]:443...
* Connected to google.com (2001:4860:4802:32::78) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to google.com:443 
* Closing connection
curl: (35) Recv failure: Connection reset by peer
```
