### ISSUE TITLE
Override remove from inner directories lies about successful removal

### ISSUE THREAD

**Issue by pravic** [rust-lang-nursery/rustup.rs#339]
> t:\hello-rs\windows\target\release>rustup override list
**T:\hello-rs\windows**                             nightly-x86_64-pc-windows-msvc

>**t:\hello-rs\windows\target\release**>rustup override remove
info: override toolchain for 't:\hello-rs\windows\target\release' **removed**
t:\hello-rs\windows\target\release>rustup override remove
info: override toolchain for 't:\hello-rs\windows\target\release' **removed**

> t:\hello-rs\windows\target\release>cd ..
t:\hello-rs\windows\target>rustup override remove
info: override toolchain for 't:\hello-rs\windows\target' removed
t:\hello-rs\windows\target>rustup override remove
info: override toolchain for 't:\hello-rs\windows\target' removed

>t:\hello-rs\windows\target>cd ..
**t:\hello-rs\windows**>rustup override remove
info: override toolchain for 't:\hello-rs\windows' **removed**
**t:\hello-rs\windows**>rustup override remove
info: **no override** toolchain for 't:\hello-rs\windows'

Meta:
> rustup 0.1.6

**Comment by brson** [comment]
Thanks for the report. IMO calling `rustup override remove` from a subdirectory of an override should report an error, not try to remove the parent directory override.

**Comment by pravic** [comment]
> should report an error, not try to remove the parent directory override.

+1

**Comment by Diggsey** [comment]
I think this will be fixed as a side effect #420

**Comment by pravic** [comment]
Nope, it was not fixed still (0.1.12).

**Comment by Diggsey** [comment]
@pravic #420 hasn't been merged yet ;)

**Comment by brson** [comment]
Fixed.
