### ISSUE TITLE
Switch from hyper to curl

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#344]
Hyper doesn't support HTTP proxies, while curl does.

**Comment by brson** [comment]
Not sure if this should block an initial release, but it does seem important.

**Comment by maximih** [comment]
A lot of companies are using proxies for internet access so I think this is very important.

**Comment by eminence** [comment]
the other option would be to teach hyper about proxies, but that seems like way more work than switching to curl

**Comment by maximih** [comment]
FWIW, there is > 1 year old issue on hyper regarding proxy support in the client: https://github.com/hyperium/hyper/issues/531

**Comment by xen0n** [comment]
I'm definitely in favor of this because of the proxy support, but the [`curl` crate](https://github.com/carllerche/curl-rust) declares an unstable API, also it didn't provide any notes on Windows support. However seeing the amount of work needed to make `hyper` support proxies it seems `curl` is the only way to go :confused:

**Comment by peschkaj** [comment]
Looks like curl does work on Windows, but maybe only with MSVC?
https://github.com/killercup/cargo-edit/issues/55#issuecomment-192583891

On Mon, Apr 25, 2016, 00:16 Wang Xuerui <notifications@github.com> wrote:

> I'm definitely in favor of this because of the proxy support, but the curl
> crate <https://github.com/carllerche/curl-rust> declares an unstable API,
> also it didn't provide any notes on Windows support. However seeing the
> amount of work needed to make hyper support proxies it seems curl is the
> only way to go [image: :confused:]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang-nursery/rustup.rs/issues/344#issuecomment-214176336>
>
-- 

Jeremiah Peschka

**Comment by brson** [comment]
@peschkaj Cargo uses libcurl, so I'm confident we can make it work on all platforms that matter.

**Comment by seanmonstar** [comment]
Proxy support is easy in the async branch, I can try to add basic support to hyper's sync branch to support this feature.

Basic functionality would be: when sending the request, if `req.url.host()` does not equal the `Host` header, then send the url in the `absolute-uri` format used for proxies. Support in the request builder could look like:

```rust
client.get("http://rustup.rs/path")
    .proxy(env::var("HTTP_PROXY").unwrap())
    .send()
```

Where `HTTP_PROXY=http://our.corporate.proxy.tld`

Would this work?

**Comment by seanmonstar** [comment]
Or perhaps it makes more sense for the proxy to be on the `Client`...

```rust
let mut client = Client::new();
client.set_proxy(host, port);
```

**Comment by brson** [comment]
@seanmonstar That works for me code-wise, though I don't know enough about the use cases to say it's sufficient. Thanks for jumping in.

**Comment by lilianmoraru** [comment]
@seanmonstar I think that's the simplest form.
For example, where I work, we use "WPAD", it's not set in "HTTP_PROXY".
Although, cargo doesn't work from the command line either because of WPAD...

**Comment by seanmonstar** [comment]
@lilianmoraru it was just an example of cargo looking at an environment variable. Whichever way cargo wants to allow configuring a proxy is out of scope of hyper supporting a proxy.

**Comment by brson** [comment]
Now that TLS support is fixed and HTTP proxy support is on the way, I'm happy to stick with hyper. It'll be good to have such a prominent project out in production using it.
