### ISSUE TITLE
Arch and OS not detected on RPi 3 with Ubuntu MATE

### ISSUE THREAD

**Issue by Phyllostachys** [rust-lang-nursery/rustup.rs#353]
I went to www.rustup.rs to see if it would work on my RPi 3 but it reported that it couldn't detect the OS.

**Comment by Phyllostachys** [comment]
Upon some more investigation, it seems that rustup.sh does properly detect armv7l and Linux, it doesn't have a source for rustc, rustc-docs, and cargo:
```
error: some components unavailable for download: 'rustc', 'rust-docs', 'cargo'
rustup: command failed: /tmp/tmp.k3xO6b3Vc4/rustup-init
```

Perhaps I jumped the gun on submitting this issue. I went ahead and made a fork, adding the support, but I don't think it is time yet to expose it.

**Comment by brson** [comment]
I'm *guessing* that this compiler just wasn't published in the 1.8 stable build and this will work if you continue to install nightly with `rustup default nightly`.

Handling toolchain install failure [more gracefully](https://github.com/rust-lang-nursery/rustup.rs/issues/275) would help make this more clear.

**Comment by Phyllostachys** [comment]
Added the pull request. Since it sounds like it is technically supported I figured that it wouldn't hurt.

**Comment by Phyllostachys** [comment]
Since it is all merged in, closing the issue.
