### ISSUE TITLE
libbacktrace doesn't build on freebsd/netbsd

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#362]
The build is currently broken because the chain-error crate links to libbacktrace, which doesn't work on freebsd and netbsd.

**Comment by alexcrichton** [comment]
upstream bug: https://github.com/alexcrichton/backtrace-rs/issues/11

**Comment by alexcrichton** [comment]
Ok, I think updating backtrace-sys to 0.1.4 should fix this
