### ISSUE TITLE
Remove multirust binary

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#373]
I thought I had already done this, but not so.

**Comment by hastebrot** [comment]
Yes, `~/.cargo/bin/multirust` is still there. Additionally the toolchains are installed into `~/.multirust`.

However the `README.md` says

>`RUSTUP_HOME` (default: `~/.rustup` or `%USERPROFILE%/.rustup`)

I made a fresh installed using `curl | sh` and it still installs the toolchains into `~/.multirust`.

**Comment by brson** [comment]
Not resolved yet.
