### ISSUE TITLE
Enabling telemetry disables rustc colors

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#378]
I guess it's capturing output? Unfortunately that disables the compiler's tty detection and disables colors altogether :(

**Comment by peschkaj** [comment]
Yup, it captures stderr and looks for compiler errors. On non-Windows platforms, we can restore color by passing `--color always`. Would it be preferrable to pass `--color always`?

**Comment by alexcrichton** [comment]
Yeah `--color always` is the only way I know of to get around this, but as you pointed out it doesn't work on Windows :(. It also gets tricky when rustc is called from a script as `--color always` may not be desired.

**Comment by peschkaj** [comment]
What if we just emit a warning when telemetry is enabled and advise people
to use `--color always` if they want color?

On Fri, Apr 29, 2016 at 12:12 PM Alex Crichton <notifications@github.com>
wrote:

> Yeah --color always is the only way I know of to get around this, but as
> you pointed out it doesn't work on Windows :(. It also gets tricky when
> rustc is called from a script as --color always may not be desired.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang-nursery/rustup.rs/issues/378#issuecomment-215785267>
>
-- 

Jeremiah Peschka

**Comment by alexcrichton** [comment]
Yeah that's a possibility, but if telemetry makes the compiler experience *worse* then it's unlikely anyone will turn it on :(

**Comment by peschkaj** [comment]
@brson - do you have any ideas on how we should handle this?

**Comment by peschkaj** [comment]
Another option we could use is to detect if `rustc` is being run interactively and then add colors back in with a `--color always`. I don't know that there's a perfect workaround for intercepting STDERR stripping colors. 

This is relatively easy to do on Linux - see [Check input is a tty](https://rosettacode.org/wiki/Check_input_device_is_a_terminal#Rust). This is more difficult to do on Windows - I'm not sure if the winapi wrappers cover checking on Windows, but we can interrogate `TokenGroups` to find out if we have an interactive security token - see [How do I detect that my application is running as service or in an interactive session?](http://stackoverflow.com/questions/2668851/how-do-i-detect-that-my-application-is-running-as-service-or-in-an-interactive-s)...

**Comment by brson** [comment]
@peschkaj I think that, when capturing output,  we should do the same check in rustup that rustc would do to determine whether to use colors, check the arguments passed to rustc don't contain `--color`, then pass a `--color` flag to override rustc's behavior.

**Comment by peschkaj** [comment]
@brson Can do!

**Comment by peschkaj** [comment]
This is implemented (for *nix) in https://github.com/rust-lang-nursery/rustup.rs/pull/394 and just needs a set of eyeballs to review.

@brson are you able to check it out?

**Comment by brson** [comment]
@peschkaj Yes, done.

**Comment by peschkaj** [comment]
Thanks!

On Wed, May 4, 2016 at 5:00 PM Brian Anderson <notifications@github.com>
wrote:

> @peschkaj <https://github.com/peschkaj> Yes, done.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang-nursery/rustup.rs/issues/378#issuecomment-217042775>
>
-- 

Jeremiah Peschka

**Comment by brson** [comment]
Fixed! Thanks @peschkaj
