### ISSUE TITLE
I went to install rustup, and the first instructions were to report an issue. So...

### ISSUE THREAD

**Issue by mwm** [rust-lang-nursery/rustup.rs#380]
> navigator.platform:
> FreeBSD amd64
> navigator.appVersion:
> 5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by brson** [comment]
Thank you! I'll update the website to detect your browser. In the meantime, I hope you found the alternate install methods.
