### ISSUE TITLE
No documentation about installation script arguments

### ISSUE THREAD

**Issue by Limeth** [rust-lang-nursery/rustup.rs#397]
The Rustup command offers arguments, which are not documented in the `README.md` file.
Run the following command to display them:
`curl https://sh.rustup.rs -sSf | sh -s -- --help`

There is also no easy way to install a specific branch (beta/nightly) without first installing the stable one. I'd suggest adding a similar argument as in
`curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=beta`

**Comment by brson** [comment]
Good catch about the arguments. Those should definitely be documented.

The default toolchain can be changed using the `--default-toolchain` option, so to install nightly:

```
 curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --default-toolchain=nightly
```

This can also be selected interactively by pressing "a" when prompted.
