### ISSUE TITLE
Make `rustup default x86_64-unknown-linux-gnu` do something smarter.

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#411]
That is, naming a toolchain by *just* the target triple might do something useful. I've seen others type the wrong thing and I've done it myself. Especially since `rustup target` takes bare target triples it's easy to confuse the two.

At the least, the `default` and `update` commands should use a heuristic to detect this and offer a suggestion.

That's probably the best way to start. With `default` if we see something that looks like a bare target, then, if the default toolchain is from a release channel, instead print an explanation and say 'did you mean `nightly-$triple`.

If the `update` command, then see if there's only one installed toolchain that we can take the channel name from and say 'did you mean nightly-$tirple`.

In both cases if we can't make a guess about what they *meant*, but it does look like a target triple, we must fall back to a generic error about toolchain specs vs target triples.

**Comment by moosingin3space** [comment]
I'll bite. Assuming there is only one `x86_64-unknown-linux-gnu` toolchain available, `rustup default x86_64-unknown-linux-gnu` should select that one. In the case of multiple toolchains, should the user then be prompted to choose the correct one?

**Comment by brson** [comment]
@moosingin3space I'd prefer that rustup not make the selection automatically, but report an error with the correct toolchain. Likewise for multiple toolchains, print them all (up to some limit perhaps). Unfortunately, @inejge already has a PR up.

**Comment by brson** [comment]
Done.
