### ISSUE TITLE
Problematic test names on 32-bit windows

### ISSUE THREAD

**Issue by Diggsey** [rust-lang-nursery/rustup.rs#427]
I can't seem to run the tests when rustup is compiled for 32-bit: specifically cargo is unable to run `cli_install_interactive-xyz.exe` and `cli_self_update-b803dd7f613778d1.exe`. I think it's because windows decides they are installers (but only for 32-bit...).

**Comment by brson** [comment]
Weird. Let's just rename them to whatever works.

**Comment by Diggsey** [comment]
Bizarrely, renaming to "cli_instal_interactive" is not enough, it still gets detected as an installer, but renaming to "cli_insta_interactive" works, so either someone at MS can't spell "installer", or it's using some kind of heuristic.

**Comment by Diggsey** [comment]
This will be fixed by #420
