### ISSUE TITLE
Description is confusing for people who don't know what multirust is

### ISSUE THREAD

**Issue by tbu-** [rust-lang-nursery/rustup.rs#43]
>The readme says "Multirust-rs is a reimplementation of multirust in rust", but it doesn't say what multirust is. For someone coming in cold, it doesn't offer any clues as to why they want to be using multirust-rs, or what they might want to use it for.

[/u/othermike on Reddit](https://www.reddit.com/r/rust/comments/3yxgtb/psa_if_you_are_writing_rust_code_on_windows_you/cyhytzv)

**Comment by LukasKalbertodt** [comment]
And maybe add a "reasons to switch from original multirust" section to `README.me`..

**Comment by brson** [comment]
readme has been rewritten.
