### ISSUE TITLE
"cargo build" failed with rust-1.8.0-x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by zoumi** [rust-lang-nursery/rustup.rs#440]
### Because the rustup-init.exe in https://www.rustup.rs/ still failed with:

> 
Welcome to Rust!
This will download and install the official compiler for the Rust programming
language, and its package manager, Cargo.
It will add the cargo, rustc, rustup and other commands to Cargo's bin
directory, located at:
E:\rustdir\bin
This path will then be added to your PATH environment variable by modifying the
HKEY_CURRENT_USER/Environment/PATH registry key.
You can uninstall at any time with rustup self uninstall and these changes will
be reverted.
WARNING: This is beta software.
Current installation options:
     default toolchain: stable
  modify PATH variable: yes
1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
1
info: syncing channel updates for 'stable-i686-pc-windows-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-r
ust-stable.toml.sha256' to 'C:\Users\*\.multirust\tmp\8lb_kpj55rarnds0_file
info: caused by: failed to make network request
info: caused by: internal error
info: caused by: ProtocolError

> 

### So I have to download the zip file of this repository,and run "cargo build" to build it.But it failed with:

> 
G:\rustup.rs-master\rustup.rs-master>cargo build
    Updating git repository `https://github.com/Diggsey/markdown.rs.git`
    Updating git repository `https://github.com/sfackler/rust-native-tls.git`
    Updating git repository `https://github.com/sfackler/schannel-rs`
 Downloading clap v2.4.3
 Downloading url v1.1.0
 Downloading tempdir v0.3.4
 Downloading scopeguard v0.1.2
 Downloading winreg v0.3.5
 Downloading regex v0.1.69
 Downloading sha2 v0.1.2
 Downloading vec_map v0.6.0
 Downloading bitflags v0.5.0
 Downloading strsim v0.4.1
 Downloading ansi_term v0.7.2
 Downloading unicode-width v0.1.3
 Downloading matches v0.1.2
 Downloading idna v0.1.0
 Downloading unicode-bidi v0.2.3
 Downloading unicode-normalization v0.1.2
 Downloading hyper v0.9.4
 Downloading userenv-sys v0.2.0
 Downloading advapi32-sys v0.2.0
 Downloading ole32-sys v0.2.0
 Downloading secur32-sys v0.2.0
 Downloading crypt32-sys v0.2.0
 Downloading backtrace v0.2.1
 Downloading backtrace-sys v0.1.4
 Downloading dbghelp-sys v0.2.0
 Downloading cfg-if v0.1.0
 Downloading traitobject v0.0.1
 Downloading typeable v0.1.2
 Downloading mime v0.2.0
 Downloading unicase v1.4.0
 Downloading cookie v0.2.4
 Downloading solicit v0.4.4
 Downloading language-tags v0.2.2
 Downloading httparse v1.1.2
 Downloading hpack v0.2.0
 Downloading advapi32-sys v0.1.2
 Downloading ktmw32-sys v0.1.0
 Downloading kernel32-sys v0.1.4
 Downloading pipeline v0.5.0
 Downloading utf8-ranges v0.1.3
 Downloading thread_local v0.2.5
 Downloading memchr v0.1.11
 Downloading aho-corasick v0.5.2
 Downloading regex-syntax v0.3.1
 Downloading thread-id v2.0.0
 Downloading walkdir v0.1.5
 Downloading tar v0.4.5
 Downloading filetime v0.1.10
   Compiling winapi v0.2.6
   Compiling utf8-ranges v0.1.3
   Compiling unicode-width v0.1.3
   Compiling matches v0.1.2
   Compiling gcc v0.3.28
   Compiling language-tags v0.2.2
   Compiling pipeline v0.5.0
   Compiling semver v0.1.20
   Compiling ansi_term v0.7.2
   Compiling cfg-if v0.1.0
   Compiling libc v0.2.11
   Compiling bitflags v0.5.0
   Compiling traitobject v0.0.1
   Compiling unicode-normalization v0.1.2
   Compiling unicode-bidi v0.2.3
   Compiling regex-syntax v0.3.1
   Compiling itertools v0.4.13
   Compiling rustc-serialize v0.3.19
   Compiling miniz-sys v0.1.7
   Compiling num_cpus v0.2.11
   Compiling memchr v0.1.11
   Compiling filetime v0.1.10
   Compiling aho-corasick v0.5.2
   Compiling rustup v0.1.10 (file:///G:/rustup.rs-master/rustup.rs-master)
   Compiling backtrace v0.2.1
   Compiling scopeguard v0.1.2
   Compiling lazy_static v0.1.16
   Compiling httparse v1.1.2
   Compiling rand v0.3.14
   Compiling backtrace-sys v0.1.4
   Compiling vec_map v0.6.0
   Compiling idna v0.1.0
   Compiling log v0.3.6
   Compiling hpack v0.2.0
   Compiling mime v0.2.0
   Compiling tempdir v0.3.4
   Compiling rustup-dist v0.1.10 (file:///G:/rustup.rs-master/rustup.rs-master)
   Compiling url v1.1.0
   Compiling typeable v0.1.2
   Compiling rustc_version v0.1.7
   Compiling strsim v0.4.1
   Compiling solicit v0.4.4
   Compiling sha2 v0.1.2
   Compiling toml v0.1.28
   Compiling clap v2.4.3
   Compiling unicase v1.4.0
   Compiling tar v0.4.5
   Compiling winapi-build v0.1.1
   Compiling ktmw32-sys v0.1.0
   Compiling secur32-sys v0.2.0
   Compiling kernel32-sys v0.2.2
   Compiling kernel32-sys v0.1.4
   Compiling ole32-sys v0.2.0
   Compiling advapi32-sys v0.2.0
   Compiling dbghelp-sys v0.2.0
   Compiling advapi32-sys v0.1.2
   Compiling shell32-sys v0.1.1
   Compiling flate2 v0.2.14
   Compiling user32-sys v0.1.2
   Compiling userenv-sys v0.2.0
   Compiling crypt32-sys v0.2.0
   Compiling walkdir v0.1.5
   Compiling time v0.1.35
   Compiling term v0.4.4
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.5
   Compiling schannel v0.0.2 (https://github.com/sfackler/schannel-rs#d16f7949)
   Compiling winreg v0.3.5
   Compiling regex v0.1.69
   Compiling error-chain v0.1.10 (file:///G:/rustup.rs-master/rustup.rs-master)
   Compiling native-tls v0.1.0 (https://github.com/sfackler/rust-native-tls.git#
a3d03b6a)
   Compiling cookie v0.2.4
   Compiling hyper v0.9.4
   Compiling markdown v0.1.2 (https://github.com/Diggsey/markdown.rs.git#d56d7ca
d)
   Compiling rustup-utils v0.1.10 (file:///G:/rustup.rs-master/rustup.rs-master)
   src\rustup-utils\src\lib.rs:1:1: 1:29 error: #[feature] may not be used on the s
   table release channel
   src\rustup-utils\src\lib.rs:1 #![feature(core_intrinsics)] // For type_name().
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   src\rustup-utils\src\lib.rs:2:1: 2:25 error: #[feature] may not be used on the s
   table release channel
   src\rustup-utils\src\lib.rs:2 #![feature(fundamental)]
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
   error: aborting due to 2 previous errors
   Could not compile `rustup-utils`.
   To learn more, run the command again with --verbose.

>

**Comment by zoumi** [comment]
By the way, can anyone tell me why cargo generates so many .rlib files in project_dir\target\debug\deps? Can't it compile all libs once and collect it into some dir to reuse it later?

**Comment by brson** [comment]
The original ProtocolError you saw is fixed now so you should be able to install the standard way. The rustup build itself [requires Rust nightly](https://github.com/rust-lang-nursery/rustup.rs/issues/58)..

@zoumi Reusing rlibs is complicated because project-specific configuration can cause the code-generation to be different between cargo 'workspaces'. [Here's a recent thread on the subject](https://internals.rust-lang.org/t/is-a-shared-build-cache-a-good-fit-for-cargo/3420/7).

I think your issues are resolved. Feel free to reopen if not!

**Comment by zoumi** [comment]
@brson Thank you!
