### ISSUE TITLE
0.1.11 fails to install new toolchain "rustup toolchain install 1.6.0"

### ISSUE THREAD

**Issue by tcr3dr** [rust-lang-nursery/rustup.rs#452]
I am receiving this error on x86_64 linux:

```
+ rustup toolchain install 1.6.0-x86_64-unknown-linux-gnu
info: syncing channel updates for '1.6.0-x86_64-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-1.6.0.toml.sha256' to '/home/vagrant/.multirust/tmp/sszoa55jy97dkvg7_file
info: caused by: http request returned an unsuccessful status code: 404
```

I assume the channel listing is only for 1.8.0 (since that's the only fixed version with that toml file) but it is overeager to use it on versions lower than 1.8.0?

**Comment by tcr3dr** [comment]
Sidenote: is there a direct download URL for older versions of rustup-init? I want to pin 0.1.10 directly in my Vagrantfile (for example) but I can't divine the URL for it, if it exists. e.g.:

```
https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/0.1.10/rustup-init
```

**Comment by brson** [comment]
This is a regression. rustup should fall back to a different download strategy for versions prior to 1.8. This fallback is even in the test suite so I'm not sure what's going on.

@tcr3dr There are no release archives for rustup at present. Previous release binaries are discarded. I originally *intended* rustup to be simple enough to upgrade without worrying about it, but it's clear keeping past versions available would help with contingencies.

**Comment by brson** [comment]
I'm looking into this and see what's going wrong. The server is returning error 403 but the fallback code only checks for 404. I'll have a patch up soon.
