### ISSUE TITLE
Can't compile with old version of itertools

### ISSUE THREAD

**Issue by saghm** [rust-lang-nursery/rustup.rs#459]
When compiling the latest release (0.1.11) from the tarball with the nightly-2016-05-11 compiler, I get the following error:

```
/home/saghm/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218:1: 224:2 error: type mismatch resolving `<<J as std::iter::IntoIterator>::IntoIter as std::iter::Iterator>::Item == <I as std::iter::IntoIterator>::Item`:
 expected type parameter,
    found associated type [E0271]
/home/saghm/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218 pub fn merge<I, J>(i: I, j: J) -> Merge<I::IntoIter, J::IntoIter>
                                                                                             ^
/home/saghm/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218:1: 224:2 help: run `rustc --explain E0271` to see a detailed explanation
/home/saghm/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218:1: 224:2 note: required by `adaptors::Merge`
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `itertools`.

To learn more, run the command again with --verbose.
```

Updating to the latest itertools (0.4.15) fixes the issue. (For some reason, the default version selected by cargo for me is 0.4.13; I honestly don't have any idea why it is picking a number that is neither in Cargo.toml or the latest semver compatible release, which would be the two most intuitive choices to me).

**Comment by brson** [comment]
This is caused by upstream Rust breakage. Cargo is picking 0.4.13 because it's in the lockfile. Since there's a new version out this can be fixed by running `cargo update`.

**Comment by saghm** [comment]
I originally tried that but was getting an issue with a different package. It seems to be gone now, so the latest nightly must have fixed it.
