### ISSUE TITLE
Completing cargo crates with racer is broken with multirust-rs

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustup.rs#46]
The problem seems to be that racer is expecting the cargo dir to be in `.multirust/toolchains/<toolchain>/cargo`, while in multirust-rs it's in `.multirust/cargo`.

```
DEBUG:racer::cargo: get_cargo_rootdir root is "/home/snake/.multirust/toolchains/nightly/cargo"
DEBUG:racer::cargo: get_versioned_cratefile: cargo rootdir is "/home/snake/.multirust/toolchains/nightly/cargo"
ERROR:racer::cargo: ERROR!: Error { repr: Os { code: 2, message: "No such file or directory" } } src/racer/cargo.rs 403
```

I'm not sure whether this deviation is an oversight or a deliberate choice. If it's the latter, then perhaps explicit support for multirust-rs vs multirust needs to be added to racer.

**Comment by Diggsey** [comment]
Have you tried setting `CARGO_HOME` to the correct location?

**Comment by crumblingstatue** [comment]
> Have you tried setting CARGO_HOME to the correct location?

Ah yes, that works!

However, it is not documented clearly anywhere that you have to do this extra step when using multirust-rs vs. multirust.

Is there a good reason for this deviation from multirust?

If so, then perhaps it should be mentioned in the README that you must set CARGO_HOME when using racer with multirust-rs.

**Comment by brson** [comment]
@phildawes do you know if this is solved?
