### ISSUE TITLE
rustup: need 'file' (command not found)

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#466]
Right now the shell script downloaded needs the `file` command. While usually present some environments, like empty docker containers, don't have this by default. Would it be possible to drop this dependency?

**Comment by brson** [comment]
This is a frustrating dep. It's used to distinguish the 32-bit userspace on 64-bit linux, a really niche case, but it's on the common linux detection path. I'd love a better way to do this detection, though maybe we can default to assuming you aren't using 32-bit userspace, print a warning about being unable to detect it.

**Comment by frewsxcv** [comment]
For reference, [here is the line in question](https://github.com/rust-lang-nursery/rustup.rs/blob/51d0e38d85958c89ba06a922e46a92e360069ce3/rustup-init.sh#L165).

**Comment by inejge** [comment]
Would `ldd` work? Assuming that the script keeps using `/usr/bin/env` as the target, and that it is dynamically linked, then

```bash
ldd "$_bin_to_probe" | grep -q '/lib.*ld-.*x86[_-]64'
```

should work on any combination of 32-bit, 64-bit, glibc and musl. (For musl, the installation should have linked `ldd` to its dynamic loader.) The detection fails if  `env` is, e.g., statically linked `busybox` in disguise, but I'm not sure that's a viable environment for rustup.

**Comment by brson** [comment]
[Fixed](https://github.com/rust-lang-nursery/rustup.rs/blob/master/rustup-init.sh#L166)

**Comment by petems** [comment]
I just hit this today, runing rustup on a Centos 7 Docker container:

```
[root@6715963ff905 ~]# curl -sSf https://static.rust-lang.org/rustup.sh | sh
rustup: need 'file' (command not found)
```

Is there something special I need to do to catch this?

**Comment by frewsxcv** [comment]
@petems You're attempting to install [rustup.sh](https://github.com/rust-lang/rustup.sh), which is different from rustup.rs (this repository)

**Comment by 0x78f1935** [comment]
Within a docker container I encountered the same issue:
```
Step 9/23 : RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh
 ---> Running in bbe97ff86e0c
rustup: need 'file' (command not found)
The command '/bin/sh -c curl -sSf https://static.rust-lang.org/rustup.sh | sh' returned a non-zero code: 1
```
