### ISSUE TITLE
Bootstrapping script has no meaningful --help

### ISSUE THREAD

**Issue by vi** [rust-lang-nursery/rustup.rs#469]
```
$ curl https://sh.rustup.rs -sSf > rustup.sh
$ chmod +x rustup.sh
$ ./rustup.sh --help
info: downloading installer
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 110
rustup: command failed: curl -sSfL https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init -o /tmp/tmp.BHBSSN9DAL/rustup-init
```

I expected to get list of options for this script, not just beginning of the installation itself.

**Comment by brson** [comment]
This is because the script delegates all argument handling to rustup-init, including `--help`. It would probably be more usable to duplicate the `--help` message in the script.

**Comment by vi** [comment]
Options regarding to how (curl? wget? verbose mode?) and which (platform detection) rustup-init to download are obviously need to be interpreted by this script.

**Comment by Diggsey** [comment]
The bootstrapping script can print usage information now.
