### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by nagisa** [rust-lang-nursery/rustup.rs#474]
```
▪~/.cargo/bin/rustup toolchain add nightly
thread '<main>' panicked at 'internal error: entered unreachable code', src/rustup-cli/rustup_mode.rs:42
stack backtrace:
   1:     0x55f7165d8ed0 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x55f7165e116b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x55f7165e0df3 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x55f7165c72ef - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x55f716210aff - std::sys_common::unwind::begin_unwind::h65390c63b501d6ed
   6:     0x55f7161f8513 - rustup_init::rustup_mode::main::h904c4ed7acbad99d
   7:     0x55f7161f0665 - rustup_init::run_multirust::h70cbf6663515e18b
   8:     0x55f7161efae1 - rustup_init::main::h81d74e5ca7cf36c2
   9:     0x55f7165e0a34 - std::sys_common::unwind::try::try_fn::h04c0c89e4add6cc4
  10:     0x55f7165d821b - __rust_try
  11:     0x55f7165e047b - std::rt::lang_start::h61f4934e780b4dfc
  12:     0x7f235f9cf740 - __libc_start_main
  13:     0x55f7161ef9d4 - <unknown>
```

**Comment by kbknapp** [comment]
I think it's as simple as adding a line [directly after this one](https://github.com/rust-lang-nursery/rustup.rs/blob/c6e430a0e3598071ffc5f2c20bd6a2cdcc0f2b3f/src/rustup-cli/rustup_mode.rs#L41) which contains:

```rust
("add", Some(m)) => try!(update(cfg, m)),
```

**Comment by nagisa** [comment]
@kbknapp the problem here is that user input can trigger a unreachable. Every typo will become an internal error rather than a proper “unknown subcommand: banana.\nnote: did you mean install”

**Comment by Diggsey** [comment]
@nagisa `clap` handles command line parsing, so typos will normally be caught earlier. In this case the problem is just that the clap config doesn't match up with the handling code.

**Comment by brson** [comment]
Ugh, that's like the third of these synonyms I've missed. Should have added tests...

**Comment by brson** [comment]
https://github.com/rust-lang-nursery/rustup.rs/pull/477

**Comment by kbknapp** [comment]
@brson or used [aliases](http://kbknapp.github.io/clap-rs/clap/struct.App.html#method.aliases) :stuck_out_tongue_winking_eye: 

Full disclosure, that's a newly implemented feature, so they haven't seen a lot of use.
