### ISSUE TITLE
rustup-init x86_64-pc-windows-gnu can't find zlib1.dll on Windows 10

### ISSUE THREAD

**Issue by nabor** [rust-lang-nursery/rustup.rs#485]
No problem with the i686-pc-windows-gnu version

**Comment by brson** [comment]
Thanks for the report. Wonder where that dynamic dep is coming from...

**Comment by cuviper** [comment]
Looks like `curl-sys` requires `zlib-sys`, and indeed both builds have `inflate*` calls from `Curl_*` functions.  But for some reason only the i686 build got a static zlib.  Perhaps your build roots have different libraries installed already and getting detected?

**Comment by Philipp91** [comment]
To everyone getting this error because they just double-clicked rustup-init.exe downloaded for x86_64-pc-windows-gnu: For your MinGW's zlib1.dll to be on the PATH, you need to launch the installer from a MinGW shell (with a command like `./rustup-init.exe`). Also, it might still detect your -msvc, so you need to customize the installation to get your -gnu toolchain.

**Comment by zengxs** [comment]
Is any possible to link zlib static?

**Comment by cogman** [comment]
I was not getting this previously but now I've started to get it as of yesterday.

**Comment by lozh** [comment]
If you are using cygwin there is a package: `mingw64-x86_64-zlib` that puts the dll in `/usr/x86_64-w64-mingw32/sys-root/mingw/bin/zlib1.dll`

I copied this to `~/.multirust/toolchain/nightly-x86_64-pc-windows-gnu/bin` and things worked. I expect you could add the other directory to your path too.

**Comment by liuchong** [comment]
The same problem here, just downloaded the 64-gnu version on windows and double clicked it, the it reported missing of zlib1.dll :joy_cat:

**Comment by Diggsey** [comment]
Just downloaded the latest binary and ran it through dependency walker, which did not find a reference to `zlib1.dll`, so I'm assuming this is fixed.

**Comment by thepperson** [comment]
I am experiencing this issue with stable-x86_64-pc-windows-gnu. zlib1__.dll is the dll not found for rust-lld.exe

**Comment by kinnison** [comment]
@thepperson If you're using the gnu toolchain, you should try and make sure that the appropriate mingw libraries are present on your system.  Sadly we're not the right people to advise you on how to do that, you could try the Rust reddit or the users forum.

**Comment by thepperson** [comment]
Copying the zlib dll (from http://www.winimage.com/zLibDll/) to .rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\bin\zlib1__.dll seems to have worked
