### ISSUE TITLE
historical nightlies get 404

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang-nursery/rustup.rs#487]
In trying to install a history nightly, like:

```
> rustup update nightly-2016-02-11
```
I am getting a 404.  I looked in the directory to confirm that the build failed that day, but it appears to have succeeded:

https://static.rust-lang.org/dist/2016-02-11/

But the particular file rustup is looking for isn't there:

```
error: could not download file from 'https://static.rust-lang.org/dist/2016-02-11/channel-rust-nightly.toml.sha256' to '/Users/jturner/.multirust/tmp/746z4ulh9xnbk95b_file
info: caused by: http request returned an unsuccessful status code: 404
```

I had a quick chat with @alexcrichton, and mentioned that this may be a possible bug where rustup doesn't support the earlier build artifacts, yet.

**Comment by dzamlo** [comment]
There is the same issue when trying to install a specific version of rust for example:
```
$ rustup install 1.3.0
info: syncing channel updates for '1.3.0-x86_64-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-1.3.0.toml.sha256' to '/home/loic/.multirust/tmp/jkly3tjqktf4sf6i_file
```

**Comment by brson** [comment]
Yes, same problem as https://github.com/rust-lang-nursery/rustup.rs/issues/502. The fallback from v2 to v1 manifests is broken.
