### ISSUE TITLE
Man pages

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rustup.rs#490]
It would be great to have a command of the form

`rustup man [TOOLCHAIN] MAN_PAGE`

that displays the man page `MAN_PAGE` (e.g. rustc, cargo) for either the active toolchain or the specified `TOOLCHAIN` if given.

**Comment by brson** [comment]
Yeah this should probably exist, though I'd like to have a solution that works reliably on Windows.

**Comment by alexreg** [comment]
Do the man pages get installed on Windows? Perhaps Unix platforms could display the man page using `man`, but Windows could open an HTML-rendered version in the browser.

**Comment by brson** [comment]
I think it would make sense for upstream Rust to generate HTML versions of the man pages and include them in the docs.

**Comment by brson** [comment]
Based on existing commands I'd expect this to look like `rustup man <program> [--toolchain]`. This should be relatively easy to implement: add the command to `rustup_mode.rs`; lookup the toolchain dir; then just run the command and report any errors.

**Comment by theindigamer** [comment]
Is this already taken? Otherwise, I'd like to do it as a first contribution.

**Comment by brson** [comment]
@theindigamer It's all yours!

**Comment by theindigamer** [comment]
Sorry if these questions sound very naive/elementary to you:

1. Any particular advice for getting started? I've read the `rustup_mode.rs` file and have spotted a few places to make additions such as the `App::new("rustup")` and `match matches.subcommand()`. I also need to add a function `fn man(cfg: &Cfg, m: &ArgMatches) -> Result<()>`.
2. Should the specification have `<command>` (like `rustup which`) or `<program>`? Can you give a couple of examples (with/without the toolchain)?
3. Also, there aren't actual `man` pages for `rustc`,`cargo` etc., or am I wrong about this? As I understand it, the `man` subcommand is just supposed to display the corresponding `help` menu.

**Comment by sanmai-NL** [comment]
Maybe the need and the requirements for this feature could use some more thought?
I personally don't see the advantage over the usual `man` invocation. Is this supposed to become something else than the `-h`/`--help` option used in various contexts (e.g., subcommand)?

**Comment by brson** [comment]
> I personally don't see the advantage over the usual man invocation.

rustup doesn't install the toolchain-specific Rust man pages to the system so running `man rustc` or `man cargo` is just an error today. This command allows the toolchains' man pages to be multiplexed like the toolchains' binaries.

> Is this supposed to become something else than the -h/--help option used in various contexts (e.g., subcommand)?

Yes. This is for the Rust toolchain man pages, like `rustc`, `cargo`, `rustdoc`; `-h` is for help with the rustup tool.

**Comment by brson** [comment]
@sanmai-NL Personally, I also wish we could just discard the man pages, but it doesn't seem like a position that can be maintained. On Unix people expect man pages to exist, and some distros will just write them themselves if we don't provide them, so they are going to continue to be a thing I think, so I reluctantly think rustup should make them accessible.

**Comment by theindigamer** [comment]
Apologies for the delay. I think some code written down for the `fn man` but how do I go about testing it? There is no binary for `rustup` generated by compilation as far as I can tell, only a `librustup.rlib` and a `rustup-init`.

**Comment by brson** [comment]
@theindigamer The way I usually test is by running `cargo run --release -- -y`, which will run `rustup-init` to install rustup to your system. Then just run rustup normally to test.

It's possible to break your own rustup installation this way but rustup is easy to reinstall when that happens.

**Comment by theindigamer** [comment]
I have made the changes here:
https://github.com/rust-lang-nursery/rustup.rs/compare/master...theindigamer:man-subcommand

Should I submit a PR or are there other changes to be made?

**Comment by brson** [comment]
@theindigamer That looks about right! Please submit a PR.

**Comment by theindigamer** [comment]
#616

**Comment by brson** [comment]
Fixed!
