### ISSUE TITLE
Command to get toolchain path

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rustup.rs#491]
The old `multirust` (script) had a `ctl` command that allowed you to get the default toolchain, active toolchain, and path for any given toolchain. Is there a way to do this in rustup? If not, it would be a nice feature to add, for scripting in particular.

**Comment by brson** [comment]
There's no way to do this presently. `ctl` was an implementation detail of multirust and I didn't expect it to be used for scripting. If you want the active toolchain path you can run `rustup which rustc` and derive it from that. If you need more precise information I'm interested to know what exactly and for what purpose.

**Comment by alexreg** [comment]
Yeah, that’s the solution I was considering. My use case was actually for a script for viewing Rust man pages for the current toolchain.

**Comment by Diggsey** [comment]
Dupe of #450
