### ISSUE TITLE
Downloads fail constantly (and badly?)

### ISSUE THREAD

**Issue by archer884** [rust-lang-nursery/rustup.rs#493]
No idea why this happens, but I often get the first two or three downloads and then fail to get the third or fourth, at which point I end up cancelling and starting over with the first two or three again. Feels kind of mean to hammer a server that already apparently can't provide a download with requests for the same files again and again... Maybe that's not what's happening? If not, it might be a good idea to report that instead of saying "downloading component 'rustc'" for the fortieth time.

Otherwise, it might be cool to keep the files successfully downloaded for my (inevitable) next attempt.

**Comment by peschkaj** [comment]
Thanks for bringing this up.

Could you provide us with a little bit more information: 
* What's the `rustup` version you're using?
* Can you paste the console output?

**Comment by archer884** [comment]
Version: rustup 0.1.9 (f3b60f5 2016-05-07)

I was originally going to say "probably not" in response to your second request, but I thought, "Meh, I'll try it and see if it screws up again..." It did. :P

    C:\src\project [branch-name-here ≡]> rustup update
    info: syncing channel updates for 'stable-i686-pc-windows-gnu'
    info: syncing channel updates for 'nightly-i686-pc-windows-gnu'
    info: downloading component 'rustc'
    47.0 MiB /  47.0 MiB (100 %)   4.9 MiB/s ETA:   0 s
    info: downloading component 'rust-std'
    59.5 MiB /  59.5 MiB (100 %)   9.3 MiB/s ETA:   0 s
    info: downloading component 'rust-docs'
    6.2 MiB /   6.2 MiB (100 %)   1.5 MiB/s ETA:   0 s
    info: downloading component 'cargo'
    1.2 MiB /   3.7 MiB ( 33 %)   0 B/s ETA: Unknown

**Comment by peschkaj** [comment]
Current rustup is 0.1.12 - could you run a `rustup self update` (assuming that works) and try again?

**Comment by brson** [comment]
@archer884 Are you on windows? This sounds like a fixed bug in the network layer. If you upgrade to the most recent release it should work.

**Comment by archer884** [comment]
Yeah, that might be it. I noticed it hasn't happened since I updated.
