### ISSUE TITLE
`rustup run <version> cargo` does not work when rustup is not in path

### ISSUE THREAD

**Issue by hansihe** [rust-lang-nursery/rustup.rs#497]
Trying to use rustup without having the bin folder added to my path.

Running `rustc` directly seems to work fine, but things break when trying to run `cargo`.

```
~/g/R/test> /home/hansihe/.cargo/bin/rustup run nightly-2016-05-07 rustc --version
rustc 1.10.0-nightly (62e2b2fb7 2016-05-06)
~/g/R/test> /home/hansihe/.cargo/bin/rustup run nightly-2016-05-07 cargo --version
error: Could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
```

I saw some other issues getting similar errors, but I am unsure if the issues are related.

**Comment by brson** [comment]
I believe this will be fixed by https://github.com/rust-lang-nursery/rustup.rs/pull/402

**Comment by Diggsey** [comment]
The fix has gone in by now - please re-open if you're still experiencing the issue.
