### ISSUE TITLE
source ~/.cargo/env in .bashrc cause a machine failed as a rsync target

### ISSUE THREAD

**Issue by jarod** [rust-lang-nursery/rustup.rs#498]
because of these output in  ~/.cargo/env
```
printf "PATH environment variable set.\n"
printf "You're ready to Rust!\n\n"
```
```
$ rsync -avrpz --delete dir/ target_server:dir/
protocol version mismatch -- is your shell clean?
(see the rsync man page for an explanation)
rsync error: protocol incompatibility (code 2) at compat.c(176) [sender=3.1.1]
```
It took me some time to find the problem. 
maybe this not even an issue of rustup, but this really cause trouble to user.

**Comment by brson** [comment]
I don't quite understand what's going on here. What's causing rsync to fail?

**Comment by erickt** [comment]
Non-interactive ssh sessions can pipe binary data through stdout (like rsync), so strings being printed out during session creation can break these protocols. We should just remove those strings. Besides, as one who opens a bunch of terminals, it gets a bit noisy to announce that rust is available.
