### ISSUE TITLE
`rustup toolchain list` should only consider directories as toolchains

### ISSUE THREAD

**Issue by ipetkov** [rust-lang-nursery/rustup.rs#520]
Was pretty surprised seeing `.DS_Store` as a toolchain since I don't remember installing it ;)

```
$ rustup toolchain list
nightly-x86_64-apple-darwin (default)
.DS_Store
```

Of course one can also trick `rustup` by making an empty directory in its `toolchains` directory, but I suppose this is by design

```
$ mkdir $RUSTUP_HOME/toolchains/foo_bar
$ rustup toolchain list
nightly-x86_64-apple-darwin (default)
.DS_Store
foo_bar
```

**Comment by brson** [comment]
Haha yes. This should be an easy fix. Just change the code here to check `is_directory`.

**Comment by ipetkov** [comment]
@brson yep, already submitted a PR (#544)!
