### ISSUE TITLE
'internal error: entered unreachable code' when uninstalling a toolchain on Windows

### ISSUE THREAD

**Issue by LFalch** [rust-lang-nursery/rustup.rs#529]
I'm running Windows 10.

When trying to run `rustup toolchain uninstall stable-i686-pc-windows-gnu` with RUST_BACKTRACE=1, I got:
```
thread '<main>' panicked at 'internal error: entered unreachable code', src/rustup-cli\rustup_mode.rs:42
stack backtrace:
   0:           0x72eafa - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   1:           0x72e015 - std::panicking::default_hook::hc2c969e7453d080c
   2:           0x6f286f - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   3:           0x4248b3 - std::sys_common::unwind::begin_unwind::h65390c63b501d6ed
   4:           0x40c633 - rustup_init::rustup_mode::main::h904c4ed7acbad99d
   5:           0x4023a4 - rustup_init::run_multirust::h70cbf6663515e18b
   6:           0x401501 - rustup_init::main::h81d74e5ca7cf36c2
   7:           0x72d66d - std::sys_common::unwind::try::hae2ea22cfba6ab9a
   8:           0x72d49a - std::rt::lang_start::h61f4934e780b4dfc
   9:           0x4013b4 - _tmainCRTStartup
  10:           0x4014e7 - mainCRTStartup
  11:     0x7ffedaa18101 - IsPipeliningPossible.isra.5
```
Rustup version:
```
rustup 0.1.12 (c6e430a 2016-05-12)
```

**Comment by corvinux** [comment]
Something similar happened to me on my Linux kalix 4.3.0-kali1-amd64 #1 SMP Debian 4.3.5-1kali1 (2016-02-11) x86_64 GNU/Linux, also trying to uninstall toolchain.

root@kalix:~# rustup 
rustup 0.1.12 (c6e430a 2016-05-12)
The Rust toolchain installer

USAGE:
    rustup [FLAGS] [SUBCOMMAND]

FLAGS:
    -v, --verbose    Enable verbose output
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    show         Show the active and installed toolchains
    update       Update Rust toolchains
    default      Set the default toolchain
    toolchain    Modify or query the installed toolchains
    target       Modify a toolchain's supported targets
    override     Modify directory toolchain overrides
    run          Run a command with an environment configured for a given toolchain
    which        Display which binary will be run for a given command
    doc          Open the documentation for the current toolchain.
    self         Modify the rustup installation
    telemetry    rustup telemetry commands
    help         Prints this message or the help of the given subcommand(s)

rustup installs The Rust Programming Language from the official
release channels, enabling you to easily switch between stable, beta,
and nightly compilers and keep them updated. It makes cross-compiling
simpler with binary builds of the standard library for common platforms.

If you are new to Rust consider running `rustup doc --book`
to learn Rust.

root@kalix:~# rustup show
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.9.0 (e4e8b6668 2016-05-18)

root@kalix:~# rustup toolchain uninstall beta-x86_64-unknown-linux-gnu
thread '<main>' panicked at 'internal error: entered unreachable code', src/rustup-cli/rustup_mode.rs:42
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@kalix:~# RUST_BACKTRACE=1 rustup toolchain uninstall beta-x86_64-unknown-linux-gnu
thread '<main>' panicked at 'internal error: entered unreachable code', src/rustup-cli/rustup_mode.rs:42
stack backtrace:
   1:     0x556e1f212ed0 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x556e1f21b16b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x556e1f21adf3 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x556e1f2012ef - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x556e1ee4aaff - std::sys_common::unwind::begin_unwind::h65390c63b501d6ed
   6:     0x556e1ee32513 - rustup_init::rustup_mode::main::h904c4ed7acbad99d
   7:     0x556e1ee2a665 - rustup_init::run_multirust::h70cbf6663515e18b
   8:     0x556e1ee29ae1 - rustup_init::main::h81d74e5ca7cf36c2
   9:     0x556e1f21aa34 - std::sys_common::unwind::try::try_fn::h04c0c89e4add6cc4
  10:     0x556e1f21221b - __rust_try
  11:     0x556e1f21a47b - std::rt::lang_start::h61f4934e780b4dfc
  12:     0x7fb4100c05ef - __libc_start_main
  13:     0x556e1ee299d4 - <unknown>

**Comment by brson** [comment]
Should be fixed now.
