### ISSUE TITLE
error_chain: Display implementation should show the error's Display, not just the description

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang-nursery/rustup.rs#530]
Given the following invocation of `error_chain!`:

```rust
error_chain! {
    types {
        Error, ErrorKind, ChainErr, Result;
    }
    links {}
    foreign_links {
        git2::Error, Git2, "git error";
    }
    errors {
    }
}
```

Producing an error from a `git2::Error` and then printing that error just produces "git error", without actually printing the underlying `git2::Error`.  The Display implementation for an error produced from a foreign link should forward to the Display implementation for the linked error.

**Comment by brson** [comment]
Yes please.

**Comment by joshtriplett** [comment]
Moved to https://github.com/brson/error-chain/issues/2
