### ISSUE TITLE
ppc64le not supported

### ISSUE THREAD

**Issue by lu-zero** [rust-lang-nursery/rustup.rs#531]
Would be possible to add builds for the platform as well?

**Comment by brson** [comment]
Sure! I put a PR up at https://github.com/rust-lang-nursery/rustup.rs/pull/534

**Comment by lu-zero** [comment]
Uhm, the pr is merged but rustup is still not happy:

```
curl https://sh.rustup.rs -sSf | sh
rustup: unknown CPU type: ppc64le
```

**Comment by brson** [comment]
@lu-zero I posted [another PR](https://github.com/rust-lang-nursery/rustup.rs/pull/647) to try to fix. 

Until that's deployed you can download the installer directly from https://static.rust-lang.org/rustup/dist/powerpc64le-unknown-linux-gnu/rustup-init

**Comment by lu-zero** [comment]
That's great, thank you :)
