### ISSUE TITLE
Move error-chain to its own repo

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#533]
Being in this repo makes it look like error-chain is part of the nursery, but it is not. It probably also discourages contribution.

**Comment by notriddle** [comment]
Not to mention it's not in the top level list of files, so I thought it wasn't here.

**Comment by killercup** [comment]
I was just about to submit a PR to change the Cargo.toml of error-chain because I thought the link to this repo was a typo until I actually found the file in here 😄

**Comment by brson** [comment]
This is done. It's at https://github.com/brson/error-chain now. I'll submit a PR to rustup shortly to remove the in-tree copy.
