### ISSUE TITLE
rustup toolchain install beta-2016-05-24

### ISSUE THREAD

**Issue by corvinux** [rust-lang-nursery/rustup.rs#536]
I would like to get rust toolchain for beta-2016-05-24, but I getting this error 
root@kalix:~/source/rust# rustup toolchain install beta-2016-05-24
info: syncing channel updates for 'beta-2016-05-24-x86_64-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/2016-05-24/channel-rust-beta.toml.sha256' to '/root/.multirust/tmp/uum5w9jv6kj05hip_file
info: caused by: http request returned an unsuccessful status code: 404
http://paste2.org/44pCJcI8.

File "channel-rust-beta.toml.sha256" doesn't exist. But there is "channel-rustc-beta.sha256" .

**Comment by brson** [comment]
I don't see a beta for that date, but do see one for 2016-06-1. That's probably what you are looking for. I imagine that the beta didn't complete on 5/24, the compiler finished but not the full distribution.

**Comment by corvinux** [comment]
@brson, thank you, I will close this issue
