### ISSUE TITLE
Rename ~/.multirust to ~/.rustup.

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#537]
This is a legacy name that needs to be transitioned away from.

**Comment by mgattozzi** [comment]
I'd like to take a stab at this issue. I was wondering what this would entail changing in the code in order to make this update smooth for existing users as well as making sure all new installs will follow this convention.

**Comment by brson** [comment]
@mgattozzi The story for upgrading rustup data formats isn't very consistent right now.

For this I would suggest the following:

* At startup `~/.multirust` exists and looks valid (the configuration loads), and `~/.rustup` does not exist, just attempt the rename silently, print an error if it fails.
* If `~/.multirust` exists and looks valid and `~/.rustup` already exists, then print an error saying to the effect of 'I want to rename this dir but I can't. Help me'.

In both cases we *could* continue on error using `~/.multirust` but the complexity probably isn't worth it.

One tricky bit here is that the initial update needs to use *either* the `~/.multirust` directory so that upgrades from previous releases work, but also from the `~/.rustup` directory be defensive against downgrades and other weird scenarios. This code path is in `self_update::self_replace`.

**Comment by fenhl** [comment]
Please consider switching to the XDG Base Directory specification instead, to remove clutter from our home directories.

**Comment by flying-sheep** [comment]
can we close this please and put a 0.4 milestone on #247?

i’ll immediately start working on it once i get green light (in both cargo and here)

**Comment by brson** [comment]
@flying-sheep No we can't do that. There is an [RFC](https://github.com/rust-lang/rfcs/pull/1615) on the subject if you would like to follow.

**Comment by flying-sheep** [comment]
thanks, i already do. and why can’t we do that?

**Comment by steveklabnik** [comment]
> won’t the RFC be followed?


The RFC has not yet been accepted.

**Comment by flying-sheep** [comment]
of course, sorry. then i’ll wait until it is!

**Comment by Diggsey** [comment]
This happened.

**Comment by Siilwyn** [comment]
@Diggsey in the readme it still states `.multirust` is used though. The description of this issue is to get rid of that name right?

**Comment by johndrinkwater** [comment]
A fresh Rust install still creates ~/.multirust/

```
lrwxrwxrwx 1 john john    18 Nov  5 18:21 .multirust -> /home/john/.rustup
drwxrwxr-x 6 john john  4096 Nov  5 18:22 .rustup
```

Could this ‘legacy name’ be transitioned away quicker?
Intent of the issue seems to still be WIP, so maybe it could be reopened.
