### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustup.rs#54]
Hi @Diggsey! I'm trying to use multirust as a library, and the version on crates is pretty ancient. I'm using it from git for now, but an update could be good. :-)

**Comment by Diggsey** [comment]
Hi @kamalmarhubi, multirust is undergoing singificant changes at the moment (see the `new` branch), so I've been avoiding publishing a new version until that's been merged into master. What are you using the multirust library for out of interest?

**Comment by kamalmarhubi** [comment]
@Diggsey I'm writing a little tool to bisect for compiler issues using nightly releases, and multirust takes care of almost all the annoying parts of that. :-)

**Comment by kamalmarhubi** [comment]
@Diggsey Is there a timeline or plan to merge `new` back into `master`? What do you think the blockers are?

**Comment by Diggsey** [comment]
See #69 for an overview of what needs doing before this can happen.

**Comment by brson** [comment]
rustup has been released since this issue was filed.
