### ISSUE TITLE
PATH variable not available in non-interactive shells on Linux

### ISSUE THREAD

**Issue by pornel** [rust-lang-nursery/rustup.rs#556]
I'm trying to deploy code using Ansible, which (very indirectly) runs `cargo` via non-interactive `ssh` session.

Rustup modifies `PATH` in `~/.profile` on Linux, but AFAIK this file is only used for interactive sessions. `~/.bashrc` is used for both interactive and non-interactive sessions, so it may be a better place to modify path.

**Comment by sbstp** [comment]
Could you add a line in your `~/.bashrc` to `source ~/.profile`?

I've done some digging and found [why this is like this](https://github.com/rust-lang-nursery/rustup.rs/issues/211). Basically, for Desktop Environments.

Relevant part:
> For example if a user launches application (IDE or Emacs, for example) via desktop environment and not via command line, then the PATH will be wrong.

**Comment by Diggsey** [comment]
There's basically no good solution to this: `.profile` is about the closest there is to a per-user setting, and excepting some shells which ignore that in favour of a shell-specific file, it *should* be sourced on login.

Unfortunately, for whatever reason, ssh sessions do not run in a login shell, despite logging in the user :angry: 

For the moment at least, if you're a linux user, you're going to have to know where this needs to be sourced to meet your needs. The best we can do is make that as easy as possible.

**Comment by brson** [comment]
Another variant of https://github.com/rust-lang-nursery/rustup.rs/issues/371
