### ISSUE TITLE
Allow installing rustup without a toolchain (or allow specifying one) 

### ISSUE THREAD

**Issue by shepmaster** [rust-lang-nursery/rustup.rs#559]
I'm building some Docker containers and throwing Rust in there:

```
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
```

This will download and install stable Rust, but I need more control over which version gets installed. Specifically, I'd like to just install rustup, and then install a specific `{stable,beta,nightly}-$DATE`:

```
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-toolchains
```

I'd also be happy if I could pick a specific version straight-off:

```
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --toolchain=beta-1999-12-31
```

I'd be happy to contribute if you have a preferred solution and can give some general pointers as to where to look.

**Comment by shepmaster** [comment]
My current workaround is to:

```
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN rustup default "stable-${date}"
```

Which uses twice the disk space due to #555.

**Comment by jimmycuadra** [comment]
I have the same use case for Ruma's development environment. Not being able to pin a specific version of nightly Rust via rustup-init is causing us pain.

**Comment by jimmycuadra** [comment]
Would allowing a specific toolchain be as simple as removing [this line](https://github.com/rust-lang-nursery/rustup.rs/blob/4adf0e3ffa930fc5107c73511d758a73115ba042/src/rustup-cli/setup_mode.rs#L35), or is there something else in the code that forces rustup-init to limit the initial toolchain to a channel name?

**Comment by brson** [comment]
@jimmycuadra Yes, removing that line will allow arbitrary toolchains at install. If we do that though it will make it much easier to generate an error during install by selecting a bogus toolchain so the error handling will have to be considered. I'd be happy to take a patch that just removes that line for now.

The error handling when the default toolchain fails to install needs revisiting in general.

**Comment by ashWhiteHat** [comment]
> I'd also be happy if I could pick a specific version straight-off:

You can with following command.
```
$ curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2021-11-17
```
