### ISSUE TITLE
Picking a default windows toolchain by detecting msvc is unpredectable

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#561]
On Windows, rustup will detect whether MSVC exists, and if so will install the MSVC toolchain, otherwise GNU. That you get different software based on what happens to be preinstalled in your environment is unpredictable. As an alternative, we might instead do the detection, but always install the msvc toolchain, printing a warning with further instructions if you don't have MSVC.

cc https://github.com/rust-lang/rust-www/issues/341#issuecomment-230357757 @Diggsey @vadimcn

**Comment by retep998** [comment]
We could also ask the user what they want to do.

**Comment by brson** [comment]
@retep998 The installer already surfaces an option to change the toolchain.

**Comment by brson** [comment]
I'm in favor of changing the order the GNU/MSVC toolchains are presented and changing the final sentence of the footer to say something about why you should pick MSVC.

**Comment by brson** [comment]
*Might* want to wait until after the 1.10 release so we're not surprising people, but most stakeholders are in this thread.

**Comment by Diggsey** [comment]
I think we always default to msvc now.
