### ISSUE TITLE
Build on stable Rust

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustup.rs#58]
The main blocker for this is the use of `#[fundamental]` in the notification system. I haven't looked into it in too much detail, but I think this can be done by reducing the amount of typegineering going on. Thoughts?

**Comment by kamalmarhubi** [comment]
Ping @Diggsey, @brson. Thoughts on this?

I'm happy to replace the notification infrastructure with something more like the emitter setup in rustc. That would get the facility without the ability to call the notifiers as though they were functions. My personal feeling is that the internal ergonomics win isn't worth requiring nightly.

**Comment by brson** [comment]
Yes please! We should try to get on stable IMO.
