### ISSUE TITLE
Add `no-self-update` feature

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#597]
For distro packaging rustup self updates make no sense. [And currently cause mysterious errors](https://github.com/rust-lang-nursery/rustup.rs/issues/471). Add a cargo feature, `no-self-update` that makes `rustup update` not do a self update and `rustup self update` print "error: self-updates are disabled for this build of rustup. If you installed rustup from a package manager, then use it to update rustup."

**Comment by steveklabnik** [comment]
Historically, with Debian, `rubygems update --system` was patched out of RubyGems by debian, causing endless strife between the two camps and a "never install ruby through `apt`" mentality by Rubyists for years.

`rustup` is not as critical as `rubygems` is, but I just wanted to make sure that you're ready for people to be using two-year old versions of `rustup`....

**Comment by brson** [comment]
@steveklabnik That's a good point. It's conceivable that rustup could detect when it has a system installation and do its own self-update in a way that shadows it.

I basically think that people should not be using package managers to install rustup (the upstream installation is supposed to be dead-simple), but packagers gonna package.

Anyway, if it causes problems we'll deal with them. This is fixed.
