### ISSUE TITLE
Do something smart when user attempts to install with sudo

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#608]
Running `rustup-init` under sudo will install rustup to the *user's* home directory with the files being owned by root. This is because sudo doesn't change `HOME`. Once this happens all manner of bad things will transpire.

Not sure offhand the best way to prevent this.

As mitigation, on startup rustup could check the owner of its files and see if they are owned by another user.

cc https://github.com/rust-lang/cargo/issues/2892#issuecomment-234378169

**Comment by Diggsey** [comment]
Maybe compare the home directory from `/etc/passwd` of the current user (determined by `whoami`) with the value of the `HOME` environment variable. If they don't match, ask for confirmation before installing there. (Overridable via a `-y` flag or similar)

**Comment by brson** [comment]
@Diggsey yeah, that sounds doable!

**Comment by brson** [comment]
Fixed! Thanks again @inejge.
