### ISSUE TITLE
Installer never terminates under FISH shell

### ISSUE THREAD

**Issue by oluseyi** [rust-lang-nursery/rustup.rs#619]
Executing `curl https://sh.rustup.rs -sSf | sh` while running the FISH shell, all the components download and install, but the process fails to terminate and requires an explicit SIGKILL.

The syntax in `rustup-init.sh` is not valid FISH, so it can't be piped into the `fish` executable either.

**Comment by brson** [comment]
Thanks for the report @oluseyi.

I don't have any insight into why this might be and can't investigate right now, but it should be fairly easy to narrow down with println debugging. I wonder if it's the script or the rustup-init binary that's hanging.

**Comment by oluseyi** [comment]
Great question, @brson. I can at least look into where the hang occurs, but likely not for another day and change. I'll update this issue with any findings.

**Comment by brson** [comment]
Thanks @oluseyi !

**Comment by oluseyi** [comment]
@brson It appears that the problem is in the `if [ "$need_tty" = "yes" ]` branch within `main()`, as both the `rustup-init.sh` and the `rustup-init` binary execute and exit fine, independently. Specifically, the invocation `run "$_file" "$@" < /dev/tty` never returns under FISH, and that appears to be a deliberate side effect of FISH's merely partial POSIX compliance. See: https://github.com/fish-shell/fish-shell/issues/1826.

Technically, this is not a rustup issue, and you can feel free to close. At best I would say to include a note for FISH users, and recommend that they pass the `-y` flag to skip the prompt.

Cheers.

**Comment by jeremy-w** [comment]
I just ran this under fish on my machine, and it worked fine. Everything involved has an explicit shebang, and the curl instruction has you piping into sh, which is GNU bash 3.2.57(1) under OS X 10.11.6, so it provides the expected behavior.

Either there's been a change very recently, or something else is up with your configuration, @oluseyi.

(The .profile modification is not at all useful under fish, but, well, that's par for the course. ;) )

**Comment by brson** [comment]
Thanks s so much for the investigation @oluseyi !

I prefer to keep this open for now since it would certainly be better for you not to hit this. Maybe others will find it and chime in, figure out what exactly is going wrong.

**Comment by brson** [comment]
Is it *possible* that `sh` is actually fish (that seems crazy) or that fish is otherwise being invoked on @oluseyi 's machine?

**Comment by oluseyi** [comment]
@brson Very unlikely, since one of the things I tried was piping `rustup-init.sh` explicitly through `fish`, and it yielded syntax errors.

Also, I had it run fine on one machine and not on another. I'll look at the failing machine again, but right now my inclination is to say it was environment config.

**Comment by brson** [comment]
Perhaps fish is a red-herring here and there's actually a really unexpected bug in whatever `sh` you've got.

**Comment by oluseyi** [comment]
@brson Perhaps. I'm not really going to expend much more energy on this, but it's a useful datum to keep in mind in case I see similar quirkiness in other cases.

Thanks for the time and effort you've put into thinking about this, and for your work on rustup as a whole!

**Comment by brson** [comment]
@oluseyi understood. Thanks again.
