### ISSUE TITLE
--quiet (or dumb terminal detecting)

### ISSUE THREAD

**Issue by ketralnis** [rust-lang-nursery/rustup.rs#631]
Rustup is extremely verbose when run outside a traditional terminal, printing thousands and thousands of hash marks as part of its download status indicator.

This is particularly troublesome when its run as part of e.g. a cron job, CI system, or vagrant script

**Comment by brson** [comment]
rustup [has code](https://github.com/rust-lang-nursery/rustup.rs/blob/master/src/rustup-cli/download_tracker.rs#L61) to turn off the download status updates when it's not connected to a tty. It seems to not be working in your case. I wonder why.

**Comment by ketralnis** [comment]
Looks like I was using the old rustup.sh. Entertainingly, fixing that appears to still on break on TTY stuff but I'll file that separately
