### ISSUE TITLE
Misleading usage line for "help subcommand"

### ISSUE THREAD

**Issue by lnicola** [rust-lang-nursery/rustup.rs#632]
This is minor and might be a `clap` issue, but here it goes:

```
C>rustup help toolchain list
rustup-list
List installed toolchains

USAGE:
    rustup list
[...]

C>rustup list
error: Found argument 'list' which wasn't expected, or isn't valid in this context
```

Note that the command listed under `USAGE:` is invalid.

**Comment by brson** [comment]
Huh! I do think that is generated by clap directly. cc @kbknapp

**Comment by kbknapp** [comment]
Interesting, I think this is stemming from a bug when requesting help of a subcommand several levels deep at once. I'll look further into this and get either a fix or answer out soon.

**Comment by kbknapp** [comment]
This is fixed in https://github.com/kbknapp/clap-rs/pull/619

Once I upload the new version to crates.io I'll post back here.

**Comment by kbknapp** [comment]
v2.10.1 is uploaded to crates.io and fixes this issue.

**Comment by lnicola** [comment]
Thanks and sorry again for misreporting it.
