### ISSUE TITLE
Misleading `show` and `list` output

### ISSUE THREAD

**Issue by lnicola** [rust-lang-nursery/rustup.rs#633]
The difference between `rustup show` and `rustup toolchain list` is somewhat unclear. The output format is also rather unexpected:

```
C>rustup show
Default host: i686-pc-windows-gnu

nightly-i686-pc-windows-gnu (default)
rustc 1.12.0-nightly (1225e122f 2016-07-30)

C>rustup toolchain list
nightly-i686-pc-windows-gnu (default)
```

It's not clear that the `rustc 1.12.0-nightly` entry is the same one as `nightly-i686-pc-windows-gnu`. Perhaps adding some indentation (like a `\t` on the second line) would make the output easier to read.

**Comment by brson** [comment]
Thanks for the report!

Yes, I can see how it's not obvious those two lines are related. I am not sure my preferred solution offhand.

**Comment by Diggsey** [comment]
This has since changed to be clearer.
