### ISSUE TITLE
`rustup man cargo` fails on Windows

### ISSUE THREAD

**Issue by pravic** [rust-lang-nursery/rustup.rs#637]
> d:>rustup man cargo
> thread '<main>' panicked at 'failed to open man page: Error { repr: Os { code: 2, message: "\u{41d}\u{435} \u{443}\u{434}\u{430}\u{435}\u{442}\u{441}\u{44f} \u{43d}\u{430}\u{439}\u{442}\u{438} \u{443}\u{43a}\u{430}\u{437}\u{430}\u{43d}\u{43d}\u{44b}\u{439} \u{444}\u{430}\u{439}\u{43b}." } }', ../src/libcore\result.rs:785
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> d:>set RUST_BACKTRACE=1
> 
> d:>rustup man cargo
> thread '<main>' panicked at 'failed to open man page: Error { repr: Os { code: 2, message: "\u{41d}\u{435} \u{443}\u{434}\u{430}\u{435}\u{442}\u{441}\u{44f} \u{43d}\u{430}\u{439}\u{442}\u{438} \u{443}\u{43a}\u{430}\u{437}\u{430}\u{43d}\u{43d}\u{44b}\u{439} \u{444}\u{430}\u{439}\u{43b}." } }', ../src/libcore\result.rs:785
> 
> d:>

**Comment by Boddlnagg** [comment]
Yeah, it tries to run the `man` program, which does not exist on Windows. I think we should just disable `rustup man` on Windows. Some Windows users might not even know what a *man page* is.

**Comment by brson** [comment]
Huh, it definitely shouldn't panic. I expected it to return a reasonable error. There must be an unwrap that should be a `chain_err` somewhere.
