### ISSUE TITLE
https://rustup.rs does not respond

### ISSUE THREAD

**Issue by hsivonen** [rust-lang-nursery/rustup.rs#638]
Navigating to the URL https://rustup.rs/ (without www.) does not work. Since the page that works is at https://www.rustup.rs/, the location https://rustup.rs/ should redirect there. (Or, alternatively, the page should move to https://rustup.rs/ and https://www.rustup.rs/ should redirect there.)

**Comment by sorccu** [comment]
Here is the error visiting http://rustup.rs shows:

```
Bad query on line :

select * from zoneinfo where type='CNAME' and pdns_name='rustup.rs'
MySQL says:

Table 'caprica.zoneinfo' doesn't exist
You may want to contact our system administrator.
```

Also, the LE cert only has www.rustup.rs in it, so https://rustup.rs/ won't work without adding both names there.

**Comment by brson** [comment]
Hm. The DNS for rustup.rs is supposedly configured to forward to https://www.rustup.rs with a 302 (temp) error code.

**Comment by brson** [comment]
(And I assume I tested it at some point).

**Comment by brson** [comment]
I attempted to remove and re-add the redirect rule to the DNS configuration.

**Comment by sorccu** [comment]
http://rustup.rs seems to work now, although https://rustup.rs still doesn't. Not sure what was going on with that error but it was real and happened every time.

Doing the forwards and TLS would be really easy with CloudFlare page rules. The free plan kind of gives you a sketchy cert so the $20/m plan would be more favorable. You'd keep the LE cert between the backend servers and CloudFlare. Maybe worth thinking about since it's possible to switch without any downtime.

**Comment by brson** [comment]
Hm, well now it redirects to http://www.rustup.rs and http://www.rustup.rs does not redirect to https://www.rustup.rs

**Comment by brson** [comment]
To my surprise nginx was not configured to redirect HTTP to HTTPS. It is now.

**Comment by hsivonen** [comment]
Why is the redirect rule a DNS config thing as opposed an nginx thing? The IP addresses for with www. and without are different and the reverse for the without www version goes to EasyDNS's redirector. It seems the redirector isn't listening on 443 and probably wouldn't have the right cert if it was.

**Comment by brson** [comment]
@hsivonen Yes you are right about that. I'm going to change the DNS to point to our nginx proxy and configure it correctly.

**Comment by sorccu** [comment]
Note that the LE cert needs to be regenerated as it doesn't include the root domain, making a graceful redirect from https://rustup.rs impossible.

**Comment by brson** [comment]
@sorccu What do you mean about a 'graceful redirect'? Can rustup.rs and www.rustup.rs not be two different certs?

**Comment by sorccu** [comment]
Right, they can be different certs. I think it may do a double handshake in that case, though. Plus it sounds like more work than keeping just one cert up to date (even if automated).

**Comment by brson** [comment]
Well, right now I've got `http://rustup.rs` redirecting to `https://rustup.rs` but neither of them redirects to `www.rustup.rs`.

**Comment by brson** [comment]
Closing this as fixed in favor of https://github.com/rust-lang-nursery/rustup.rs/issues/646.
