### ISSUE TITLE
telemetry mode hangs if there are too many errors

### ISSUE THREAD

**Issue by arielb1** [rust-lang-nursery/rustup.rs#639]
## Meta

```
$ rustup -V
rustup 0.5.0 (4be1012 2016-07-30)
$ rustc -V
rustc 1.12.0-nightly (0a3180baa 2016-08-03)
$ cat ~/.multirust/settings.toml 
default_host_triple = "x86_64-unknown-linux-gnu"
default_toolchain = "nightly"
telemetry = true 
version = "12"

[overrides]
```

## STR

```
$ for i in $(seq 1 10000); do echo "fn fail() {}"; done >> so-much-fail.rs
$ rustc so-much-fail.rs 
```

## Expected Result

10000 errors are printed to standard error

## Actual Result

hang, since `telemetry_rustc` (https://github.com/rust-lang-nursery/rustup.rs/blob/4be1012/src/rustup/command.rs#L51) pipes stderr and waits, without reading from it.

moved from rust-lang/rust#34535

**Comment by brson** [comment]
Thanks for filing this. Telemetry is very underbaked right now and I don't recommend anybody use it.

**Comment by aidanhs** [comment]
Just because it could break things or because it might accidentally be collecting all of my hard drive? If the former that's fine, in general I feel capable of debugging issues if I hit them (though @arielb1 saved me for this one).

**Comment by TimNN** [comment]
Just ran into this, very annoying to debug, although I did learn a bit more about `lldb`.
