### ISSUE TITLE
Cross-compiler support

### ISSUE THREAD

**Issue by jan-hudec** [rust-lang-nursery/rustup.rs#64]
It would be nice to add support for installing standard library for additional targets to support cross-compilation. Multirust (non-rs) is adding it in https://github.com/brson/multirust/pull/112 (it appears to depend on new manifest format, that is not on the main distribution site yet, though).

**Comment by brson** [comment]
There is a wip on the 'new' branch.

**Comment by Diggsey** [comment]
This is done!
