### ISSUE TITLE
Can't remove override if the directory no longer exists

### ISSUE THREAD

**Issue by Riateche** [rust-lang-nursery/rustup.rs#642]
1. Create a directory.
2. Call "rustup override set nightly".
3. Remove a directory.

There is no way to specify path for "unset" command. If the directory does not exist and you can't "cd" to it, then the override cannot be removed.

Possible solution: implement "rustup override unset for [path]" or "rustup override unset --path=[path]".

**Comment by Boddlnagg** [comment]
Maybe `rustup override list` could check each of the directories for existence, mark those that no longer exist, show a warning and offer a command to easily remove all overrides for such paths?

**Comment by brson** [comment]
Thanks for the report!

`rustup override unset --path=` makes sense to me. Help wanted. For bonus points, @Boddlnagg 's suggestion also sounds good to me.

**Comment by Boddlnagg** [comment]
I think this can be closed now that https://github.com/rust-lang-nursery/rustup.rs/pull/650 has landed.
