### ISSUE TITLE
change "/dev/tty does not exist" to something more helpful

### ISSUE THREAD

**Issue by ketralnis** [rust-lang-nursery/rustup.rs#648]
Rustup simply dies with the error message "/dev/tty does not exist" when a TTY isn't available. This is particularly troublesome when its run as part of e.g. a cron job, CI system, or vagrant script.

It dies with a particularly unhelpful message:

```
info: downloading installer
./rustup.sh: 79: ./rustup.sh:
cannot open /dev/tty: No such device or address
```

Looking at the script, that corresponds to:

```
# The installer is going to want to ask for confirmation by
# reading stdin.  This script was piped into `sh` though and
# doesn't have stdin to pass to its children. Instead we're going
# to explicitly connect /dev/tty to the installer's stdin.
if [ ! -e "/dev/tty" ]; then
    err "/dev/tty does not exist"
fi
```

There's no way to know what's wrong or how to fix it without actually reading the script. AFAICT there's no way to proceed without a TTY other than accepting the defaults since no other options are accepted or env variables checked. So that error message could read something like:

```
err "/dev/tty not available, prompts unavailable. Run with '-y' to accept defaults"
```

**Comment by brson** [comment]
It seems like the `! -e "/dev/tty"` check is not sufficient. Do you know what check would work here and print the correct error? I agree the error message could be better.

The script passes all arguments to the `rustup-init` executable, so all options can be set non-interactively. Unfortunately it doesn't have it's own argument documentation (https://github.com/rust-lang-nursery/rustup.rs/issues/652).

Maybe

```
err "Unable to run interactively. Run with '-y' to accept defaults. Run with `--help` for additional options."
```

Assuming #652 is fixed.
