### ISSUE TITLE
Add `rustup component` subcommand

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#658]
The generalized version of `rustup target`. This command will allow the `rust-src` package to be installed once https://github.com/rust-lang/rust-buildbot/pull/102 lands. One complication here is that the `rust-src` package has a target equal to "*" in the manifests.

I think the way this might work is `rustup component add` defaults to the host target, which can resolve to "*". That way you can write `rustup component add rust-src`.

The command might have the same set of subcommands as `rustup target`, and e.g. `add` might look like

```
rustup.exe-component-add
Add a component to a Rust toolchain

USAGE:
    rustup.exe component add [OPTIONS] <component>

FLAGS:
    -h, --help    Prints help information

OPTIONS:
        --toolchain <toolchain>
        --target <target>

ARGS:
    <target>
```

**Comment by brson** [comment]
cc @Diggsey

**Comment by Diggsey** [comment]
When you say it "resolves to *", do you mean that it will do a reverse match and * will match any target specifier?

Sounds good, although we're getting a lot of subcommands :stuck_out_tongue: We might have to start showing a reduced help text with only the key features by default to avoid overwhelming users.
