### ISSUE TITLE
Turn on hyper backend by default

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#663]
I think it works! Let's turn it on and see if anything goes bad. Should be a matter of changing the `download_file_` function to prefer hyper to curl.

It would be nice if native_tls was published to crates.io though.

Once the hyper backend is live for a month or so we can disable the curl backend completely by turning off the feature of the download crate. For now I don't want to remove curl support from the download crate because I still have the notion to publish it separately as a learning tool.

**Comment by brson** [comment]
Hm, it's probably worth investigating whether there are any new revisions of native_tls, and to do a bit more due diligence by having somebody smart review the TLS integration.

**Comment by jelford** [comment]
@brson can this issue be closed in light of https://github.com/rust-lang-nursery/rustup.rs/issues/993?
