### ISSUE TITLE
Comma-separated arguments seem to be split with `rustup run`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#665]
Whenever I use `rustup run` it seems to interfere with comma-separated arguments:

```rust
$ rustup run stable rustc --emit llvm-ir,link foo.rs
error: multiple input filenames provided

$ rustc --emit llvm-ir,link foo.rs
$
```

Is there perhaps something going on with the rustup option parser?

**Comment by Diggsey** [comment]
Does separating it with `--` help?

**Comment by kbknapp** [comment]
You need to add `use_delimiter(false)` to [this line.](https://github.com/rust-lang-nursery/rustup.rs/blob/5dc483353797b24eb1f9674161aa01bbe89aca4a/src/rustup-cli/rustup_mode.rs/#L291)

[Detailed info.](http://kbknapp.github.io/clap-rs/clap/struct.Arg.html#method.use_delimiter)

**Comment by Diggsey** [comment]
@kbknapp Ah, thanks - will this combination ensure that the remaining arguments are passed through unaltered in all cases?

**Comment by kbknapp** [comment]
@Diggsey yes, by default arguments with a comma are separated into distinct arguments, i.e. `--option 'one,two,three'` becomes `--option 'one' 'two' 'three'`

The setting linked above says, don't use a delimiter at all. The delimiter can alternatively be changed a character other than a comma as well.
