### ISSUE TITLE
Sort toolchains numerically

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustup.rs#668]
1.10.0 after 1.9.0 (or before, if we do reverse numeric order).

```
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.0.0-x86_64-unknown-linux-gnu
1.1.0-x86_64-unknown-linux-gnu
1.10.0-x86_64-unknown-linux-gnu
1.11.0-x86_64-unknown-linux-gnu
1.2.0-x86_64-unknown-linux-gnu
1.3.0-x86_64-unknown-linux-gnu
1.4.0-x86_64-unknown-linux-gnu
1.5.0-x86_64-unknown-linux-gnu
1.6.0-x86_64-unknown-linux-gnu
1.7.0-x86_64-unknown-linux-gnu
1.8.0-x86_64-unknown-linux-gnu
1.9.0-x86_64-unknown-linux-gnu
```

**Comment by Boddlnagg** [comment]
That sounds like a good idea to me! The sorting happens [here](https://github.com/rust-lang-nursery/rustup.rs/blob/c143541/src/rustup/toolchain.rs#L422). I think the right way to do this is by having a custom `Ord` impl for [`Component`](https://github.com/rust-lang-nursery/rustup.rs/blob/e0e4dd3/src/rustup-dist/src/manifest.rs#L52). Do you want to try implementing this? You can probably use https://crates.io/crates/natord.

**Comment by malbarbo** [comment]
This was fixed by https://github.com/rust-lang-nursery/rustup.rs/pull/688
