### ISSUE TITLE
Issues with the downloaded executables on Win7 behind a corporate proxy

### ISSUE THREAD

**Issue by kikokikok** [rust-lang-nursery/rustup.rs#704]
Hello,

I've been having issues with downloaded executables with Rustup-rs. It seems like it when executed they freeze and create unkillable ghost processes (rustc.exe mainly).
They are all of the same size and are not of the same size than the Msi installed files.

Might be an issue with my proxy but it's the first time I encounter such an issue.

![image](https://cloud.githubusercontent.com/assets/1577981/18095022/e6370aec-6ed5-11e6-897b-e5e66e416b6d.png)

**Comment by Boddlnagg** [comment]
@kikokikok That they are all of the same size is expected/intended. All the other executables are just hardlinks to `rustup.exe` and the code changes behavior based on the name of the executable it is run as, and then calls the respective binary from the currently selected toolchain (in `.multirust\toolchains`).

This probably won't help to identify why they freeze. You can try to run `rustc.exe` from one of the toolchain directories directly, to make sure that the issue really is with `rustup`.

**Comment by kikokikok** [comment]
executing the files directly from the toolchains works fine.

**Comment by kikokikok** [comment]
something worth noting is that all our laptop are encrypted through bitlocker. didn't have any issue before trying to use it on the laptop.

**Comment by kikokikok** [comment]
Latest trial: cargo.exe & rustdoc.exe are the only one freezing from the .cargo/bin directory

**Comment by kikokikok** [comment]
It works again now...
