### ISSUE TITLE
`rustup target list` lists arm-musl targets but there is no rust-std components for them

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/rustup.rs#709]
This is misleading. People then try to get `std` for these targets and get weird error messages:

```
$ rustup target list | grep 'arm.*musl'
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armv7-unknown-linux-musleabihf

$ rustup target add arm-unknown-linux-musl
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'arm-unknown-linux-musl'
```

### Meta

```
$ rustup -V
rustup 0.6.3 (a0e2132 2016-08-28)
```

Reported in [u.r-l.o](https://users.rust-lang.org/t/arm-musl-target-error/7144).

cc @brson

**Comment by andreastt** [comment]
This is a duplicate of https://github.com/rust-lang-nursery/rustup.rs/issues/326.

**Comment by japaric** [comment]
> This is a duplicate of #326.

You are right! Closing this one.
