### ISSUE TITLE
MSVC Runtime is missing on Windows

### ISSUE THREAD

**Issue by Riateche** [rust-lang-nursery/rustup.rs#712]
When installing Rust via rustup on a clean Windows 7 x64, rustc and cargo can't be executed because msvcr120.dll is missing. Rustup reports successful install. 

After installing Visual C++ Redistributable Package for Visual Studio 2013 (x64) rustc and cargo start working.

Rustup probably should install the runtime package automatically.

**Comment by retep998** [comment]
Alternatively Rust and Cargo can use the static CRT so they don't depend on the VC++ redistributable.

**Comment by dkotrada** [comment]
Followed Instructions. And installed standalone msvc build tools 2015. msvcr120.dll is missing

:(

**Comment by kornelski** [comment]
![screen shot 2017-03-03 at 11 18 31](https://cloud.githubusercontent.com/assets/72159/23549671/3714d1c2-0005-11e7-96ce-1e0441b583f1.png)

This is still a problem.

**Comment by retep998** [comment]
@pornel On stable it is, sure, but if you switched to *nightly* you'd find that the problem is already fixed thanks to https://github.com/rust-lang/rust/pull/39837

Can someone without the VC++ 2013 redistributable who experiences this issue with the current stable confirm whether nightly fixes this?

**Comment by kornelski** [comment]
You can get a fresh VM from Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by kornelski** [comment]
Nightly works for me, yay!

**Comment by bjadamson** [comment]
Ran into this today, while looking for a solution. Thanks, I'm going to try 2013 in the mean time!

**Comment by Diggsey** [comment]
Fixed upstream
