### ISSUE TITLE
Bundled libmingwex.a doesn't contain strtok_r

### ISSUE THREAD

**Issue by kryptan** [rust-lang-nursery/rustup.rs#718]
libmingwex.a which is installed with *-pc-windows-gnu toolchains doesn't contain implementation of `strtok_r`. This and other mingw libraries are probably outdated. The latest version in mingw-w64 does contain `strtok_r`. This [causes issues](https://github.com/rust-lang/rust/issues/19519) when linking with libcurl. I think all mingw libraries should be updated to the latest version.

I don't know if this is the right repo for this issue as I don't know where is the build script which builds mingw libraries shipped by rustup.

**Comment by Diggsey** [comment]
This should be reported to rust-lang/rust if it's still an issue.
