### ISSUE TITLE
Shell prompt helper command

### ISSUE THREAD

**Issue by ijanos** [rust-lang-nursery/rustup.rs#720]
I was using `multirust ctl override-toolchain` command to show the currently selected toolchain in my shell's prompt if the current directory contains a `Cargo.toml` file, similarly to showing the current git branch if the directory is a git repository. I've found issue #491 mentioning that ctl like commands are not likely to appear in rustup. 

Would you consider this as a use case for a new rustup command or should I fall back to some other solution, like piping  rustup's output through sed?

**Comment by kbknapp** [comment]
Although not a 1:1 solution, `rustup show | tail -n 3 | head -n 1` shows something like:

```
$ rustup show | tail -n 3 | head -n 1
stable-x86_64-unknown-linux-gnu (default)
```

Which I'm sure could be cut down more if desired.

**Comment by ijanos** [comment]
Well, programming rust is fun, so I threw together a [small helper program](https://github.com/ijanos/rustup_prompt_helper) for this. I think a subcommand like `rustup show override` could still be useful for prompts and other scripting purposes, so I will leave the issue open but feel free to close it if you think this is out of scope for the rustup project.

**Comment by Diggsey** [comment]
Dupe of #491
