### ISSUE TITLE
`rustup.sh` uses ANSI color codes without checking if stdout is wired to a terminal

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang-nursery/rustup.rs#721]
This is a minor nit. This line:-

```bash
printf "\33[1minfo:\33[0m downloading installer\n"
```

in `https://github.com/rust-lang-nursery/rustup.rs/blob/master/rustup-init.sh` uses ANSI color codes. Before outputting the line, we ought to check if stdout is connected to a terminal, eg using `test` / `[`, so that users running without a terminal don't get rubbish in their logs if redirecting. Additionally, to be truly robust, we ought to then output the ANSI sequences using `tput`. However, `tput` isn't common on embedded systems built around Busybox and the like, so one needs to be quite defensive.

A strategy I've used in the past is lines [here](https://github.com/shellfire-dev/core/blob/master/init.functions) 70 through to 250. Obviously that's extensive, but it works. In addition, we seem to check for the presence of `printf` (`need_cmd printf`). That seems a little odd, as all POSIX compliant shells that I know of support it. I can't vouch for `zsh` or `ksh93`.

As an extra special super-pedantic nit, the `printf` output should be going to `stderr` as it's progress information. I'll get my coat...

**Comment by raphaelcohn** [comment]
See PR.

**Comment by gifnksm** [comment]
#725 merged. Can this issue be closed?

**Comment by raphaelcohn** [comment]
Yes
