### ISSUE TITLE
Add a flag to download Rust source code

### ISSUE THREAD

**Issue by xstevens** [rust-lang-nursery/rustup.rs#726]
It would be nice if there was flag/subcommand or default to downloading source code as well. This would help automate a workable development environment with tools like racer.

**Comment by Diggsey** [comment]
Other than `rustup component add rust-src`?

**Comment by xstevens** [comment]
@Diggsey Oh, cool. I didn't find any reference to this existing. It's not working on my Mac but this is a different problem.

```
$ rustup component add rust-src
error: toolchain 'stable-x86_64-apple-darwin' does not contain component 'rust-src' for target 'x86_64-apple-darwin'
```

**Comment by Diggsey** [comment]
Yep, it's a recent addition so unfortunately only nightlies have source packages so far.
