### ISSUE TITLE
zsh completions returning errors

### ISSUE THREAD

**Issue by Nashenas88** [rust-lang-nursery/rustup.rs#727]
When typing `rustup` followed by &lt;tab&gt; I get the following output from zsh:

```
⇒  rustup 
_rustup_cmds:1: unknown file attribute: \n
_rustup_cmds:1: unknown file attribute: \n
_rustup_cmds:1: unknown file attribute: \n
```

**Comment by traviskaufman** [comment]
Had the same issue using `oh-my-zsh` on OS X. I think it has to do with how `_rustup` declares and formats array types: 

```zsh
local -a subcommands=(
  'cmd1'
  'cmd2'
   ...
)
```

It looks like it should really be:

```zsh
local -a subcommands
subcommands=('cmd1' 'cmd2' ...)
```

More info at http://stackoverflow.com/questions/30269722/declaring-arrays-in-zsh

Modifying all of the array decls in my local `_rustup` and then running `rm -fr ~/.zcompdump ~/.zcompdump-*; source ~/.zshrc` solved it for me.
