### ISSUE TITLE
Unable to locate `rustup` binary on Docker machine

### ISSUE THREAD

**Issue by johnnyman727** [rust-lang-nursery/rustup.rs#728]
I'm hoping to install `rustup` on a Docker container.

Here are the commands I run:

```
RUN curl -s https://static.rust-lang.org/rustup.sh > /home/install.sh
RUN chmod +x /home/install.sh
RUN sh /home/install.sh -s -- --default-toolchain nightly
```

It appears to install both `cargo` and `rustc` properly but not `rustup`. Additionally, there is no `.cargo` folder created as I would expect.

**Comment by alexcrichton** [comment]
Oh the `rustup.sh` script doesn't actually install this `rustup` project. To do that you'll want to download from https://sh.rustup.rs

**Comment by grigio** [comment]
I installed rust in docker with: `curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y` but rustup isn't available

```
# rustup
bash: rustup: command not found
```

**Comment by Diggsey** [comment]
@grigio You would need to add `CARGO_HOME/bin` to your PATH.
