### ISSUE TITLE
Add 'rustup uninstall' alias

### ISSUE THREAD

**Issue by comex** [rust-lang-nursery/rustup.rs#730]
It's confusing that there's a `rustup install` equivalent to `rustup toolchain install`, but no `rustup uninstall` to match `rustup toolchain uninstall`.

(It's also a bit weird that the documentation for `rustup install` states that it's an alias for `rustup update <toolchain>`, which in turn is documented as an alias for `rustup toolchain install` - flipping between the verbs "install" and "update".)

Not sure whether `remove` should also be aliased.

**Comment by clarfonthey** [comment]
Is there going to be any progress on this?

**Comment by Diggsey** [comment]
@clarcharr PRs are welcome

**Comment by kbknapp** [comment]
It's a [one line addition](https://github.com/rust-lang-nursery/rustup.rs/blob/705c110e83c609e7901992058f0f58e26a623a4f/src/rustup-cli/rustup_mode.rs#L315). Could be a good first PR for someone.
