### ISSUE TITLE
Custom toolchains cannot be uninstalled/unlinked

### ISSUE THREAD

**Issue by pmarcelll** [rust-lang-nursery/rustup.rs#735]
[This line](https://github.com/rust-lang-nursery/rustup.rs/blob/cd0d20166fab04be043c92c8c0136bf52f3224ee/src/rustup/toolchain.rs#L75) checks whether a toolchain exists by looking up the directory, but custom toolchains use symlinks so this check fails.

**Comment by jonas-schievink** [comment]
This is pretty annoying, the only way to uninstall custom toolchains is to remove the symlink manually

**Comment by pmarcelll** [comment]
I just noticed in the changelog that it was fixed by #1201.
