### ISSUE TITLE
Support for ARM Musl targets

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang-nursery/rustup.rs#736]
[Rust now supports](https://github.com/rust-lang/rust/pull/35060) these targets:
```
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armv7-unknown-linux-musleabihf
```

Could we get support for these targets?(Although, the packages are not yet uploaded :smile: )

**Comment by jonas-schievink** [comment]
Shouldn't support for them land automatically once they're uploaded?

**Comment by brson** [comment]
The actual work here needs to be done in [rust-buildbot](https://github.com/rust-lang/rust-buildbot) but there are some bugs there preventing it from happening.

**Comment by lilianmoraru** [comment]
Alex Crichton added support for it in `rust-buildbot`.

**Comment by lilianmoraru** [comment]
@jonas-schievink I don't know how exactly `rustup` works.
I tried now: `rustup target add arm-unknown-linux-musleabi`
And I get: `error: component 'rust-std' for 'arm-unknown-linux-musleabi' is unavailable for download`.

Although, I am not sure that `arm-unknown-linux-musleabi` was already built(I just guessed since 9 hours have passed).

**Comment by lilianmoraru** [comment]
Big thanks to @alexcrichton, these targets work now:
- `arm-unknown-linux-musleabi`
- `arm-unknown-linux-musleabihf`
- `armv7-unknown-linux-musleabihf`
- `asmjs-unknown-emscripten`
- `wasm32-unknown-emscripten`

`num_cpus` as a test, compiles with all the `musl` targets but not with `emscripten`.
