### ISSUE TITLE
emscripten toolchain

### ISSUE THREAD

**Issue by ticki** [rust-lang-nursery/rustup.rs#743]

**Comment by Diggsey** [comment]
What exactly is the issue? There doesn't appear to be an emscripten target in the latest manifest?

**Comment by ticki** [comment]
I mean `rustup toolchain` should provide the `emsdk-portable` installation.

**Comment by Diggsey** [comment]
There's no `emsdk-portable` toolchain in the manifest yet either? Will that arrive with the next successful nightly?

**Comment by ticki** [comment]
ping @brson.

**Comment by lilianmoraru** [comment]
@alexcrichton Added the targets to `rust-builbot`.
These 2 should work now:
- `rustup target add asmjs-unknown-emscripten`
- `rustup target add wasm32-unknown-emscripten`

**Comment by alexcrichton** [comment]
Indeed! done

**Comment by chriskrycho** [comment]
Happy to open a separate issue if it's helpful, but `rustup target add asmjs-unknown-emscripten` and `rustup target add wasm32-unknown-emscripten` both fail currently with:

```
error: component 'rust-std' for 'asmjs-unknown-emscripten' is unavailable for download
```

**Edit:** sorry, I lied; I didn't realize `rustup target` was specific to what override/default you have set. :grimacing:
