### ISSUE TITLE
Parallel builds of crate dependencies leads to intermittent linker errors

### ISSUE THREAD

**Issue by tcosprojects** [rust-lang-nursery/rustup.rs#746]
### Summary

While cargo is compiling dependencies I'm seeing intermittent linker errors. It appears the issue is caused by how cargo uses job objects on windows detailed in this issue: rust-lang/rust#33145

Cargo issue is here: https://github.com/rust-lang/cargo/issues/3161

@alexcrichton mentioned that rustup.rs uses job objects, may be affected by this issue as well and that I should open an issue here too.
### System info

```
Windows 10 x64

rustc 1.12.0 (3191fbae9 2016-09-23)
binary: rustc
commit-hash: 3191fbae9da539442351f883bdabcad0d72efcb6
commit-date: 2016-09-23
host: i686-pc-windows-msvc
release: 1.12.0

rustup 0.6.3 (a0e2132 2016-08-28)

cargo 0.13.0-nightly (109cb7c 2016-08-19)
```

**Comment by alexcrichton** [comment]
I posted a diagnosis (https://github.com/rust-lang/cargo/issues/3161#issuecomment-251508290) in Cargo, but I think we'll just want to copy https://github.com/alexcrichton/rustjob into Cargo and then copy that into rustc

**Comment by alexcrichton** [comment]
er, copy it into rustup*

**Comment by alexcrichton** [comment]
I've posted a PR to fix this issue -- https://github.com/rust-lang-nursery/rustup.rs/pull/984
