### ISSUE TITLE
rustup run cargo calls rustc on PATH

### ISSUE THREAD

**Issue by tspiteri** [rust-lang-nursery/rustup.rs#749]
My `$PATH` is `...:/usr/bin:...:/home/user/.cargo/bin`. There are rustc and cargo binaries from the distro in /usr/bin, so by default, the distro binaries are used.

If I run `rustup run nightly cargo build`, cargo from ~/.cargo/bin is used, but in turn it uses rustc from /usr/bin. It would be great if using rustup run would make sure that rustup's cargo uses rustup's rustc instead.

**Comment by valarauca** [comment]
FYI this is a duplicate issue to

https://github.com/rust-lang-nursery/rustup.rs/issues/702

**Comment by tspiteri** [comment]
This seems to be solved with the latest rustup, as the toolchain path is now being prepended to PATH when running cargo.
