### ISSUE TITLE
Support download continuation (similar to `curl -C -`)

### ISSUE THREAD

**Issue by kennytm** [rust-lang-nursery/rustup.rs#750]
When you use `rustup update` to update a channel, all components must be downloaded successfully in order for the update to complete. If any component failed to download, the whole channel will fail as well. Therefore, on an unstable network, it is basically impossible to update.

A better option is to save the partially downloaded data. This way even if the download was interrupted, the user could still resume.

---

``` bash
$ rustup -V
rustup 0.6.3 (a0e2132 2016-08-28)
```

**Comment by jelford** [comment]
@kennytm I think this should be fixed by #958 & #1020 which move download staging to a persistent directory and support resumption. Does that more or less fit the bill?

**Comment by kennytm** [comment]
Yes. Thanks 😊
