### ISSUE TITLE
rebranding 🚲 🏠

### ISSUE THREAD

**Issue by durka** [rust-lang-nursery/rustup.rs#757]
Is it too late to consider renaming the tool itself? It's named the same as the historical rustup.sh tool, which is still listed as the official installation method even though "everyone" recommends rustup.rs, which [continues to cause confusion](https://www.reddit.com/r/rust/comments/55o54l/hey_rustaceans_got_an_easy_question_ask_here/d8p2vib).

**Comment by steveklabnik** [comment]
I would prefer to finally ship rustup, so we can just never speak of .sh again.

**Comment by durka** [comment]
We would still have to speak of it, i.e. "We've shipped rustup! before installing rustup, please uninstall rust if you previously uninstalled it with rustup."

**Comment by UtherII** [comment]
Can't you change rustup.sh so it installs rustup.rs instead ?
If not, you can probably just change the rustup.sh script so it only display a error/warning message suggesting using rustup.rs.

**Comment by srinivasreddy** [comment]
I wish i could rename this tool as  `Prep`.  :smile:

**Comment by bakirov** [comment]
Please, do not: `rustup` is a cool name and very pronounceable.

**Comment by est31** [comment]
rust wasn't renamed when 1.0 was released, and it survived it. I think rustup will survive this too.
