### ISSUE TITLE
Download progress swamps terminal on MinGW

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustup.rs#76]
In a MinGW terminal I ran `multirust update`, and the new download progress counters look like they didn't correctly overwrite themselves so the output was just swamped with updates:

![https://i.imgur.com/dBVSCGV.png](https://i.imgur.com/dBVSCGV.png)

**Comment by crumblingstatue** [comment]
Related to #71 .

I'm not sure what's going on here. `StdoutTerminal::carriage_return()` should take care of resetting the cursor position to the beginning of the line, unless I'm either misinterpreting its function, or it's not working correctly on mingw terminals.

This should be less severe once #80 gets merged, as the information is printed only once per second. It would still be desirable for the line overwriting to work properly on mingw terminals though.

If someone has a mingw terminal and some time, investigating this would be appreciated.

**Comment by brson** [comment]
I believe this is fixed?

**Comment by Diggsey** [comment]
Yup, although until Stebalien/term#58 is fixed, there's no download progress at all.
