### ISSUE TITLE
Will muslrust be surpported by rustup in future?

### ISSUE THREAD

**Issue by zoumi** [rust-lang-nursery/rustup.rs#774]
I need to run rustlang programs in some OS which is older than the OS I compile the programs.
So,there is a dynamic lib error:

    /lib64/libc.so.6: version `GLIBC_2.17' not found (required by myserver)

And I find a solution:
    https://doc.rust-lang.org/book/advanced-linking.html

It says I need to compile a diy rust. But I would like to use rustup to install rust.
So....will muslrust be surpported by rustup in future?

**Comment by steveklabnik** [comment]
rustup does support MUSL already; the book doesn't point that out because rustup is still in beta.

**Comment by zoumi** [comment]
Any tip on how to install it?

**Comment by zoumi** [comment]
I get it: 

    rustup target add x86_64-unknown-linux-musl
Thanks.
