### ISSUE TITLE
Rustup doesn't play nicely with Sudo

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rustup.rs#784]
Example:

```
sudo -Hs -u _homebrew cargo
error: could not crate home directory: '/usr/local/.multirust'
info: caused by: Permission denied (os error 13)
```

Ideally, sudo (at least when used with the `-H` option) should use the toolchain/settings for the parent user, not root/_homebrew/whatever use you're sudoing as.

Also, note the typo "crate" (should be "create").

Note: this is on OS X 10.12.

**Comment by alexreg** [comment]
I've just (perhaps) solved this by adding `RUSTUP_HOME`, `RUSTUP_TOOLCHAIN`, and `CARGO_HOME` to `env_keep` in my sudoers file, but is this the right approach?

**Comment by Diggsey** [comment]
This is the correct approach, and is only necessary for the variables you've overridden. (The HOME var is automatically kept, and the others are by default derived from that)
