### ISSUE TITLE
rustup fails because of checksum mismatch

### ISSUE THREAD

**Issue by gruszczy** [rust-lang-nursery/rustup.rs#785]
I saw bunch of older issues about this and it's happening to me right now too:

$ rustup toolchain install nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: update not yet available, sorry! try again later
error: checksum failed, expected: '12a28645967990bccb57a259a30d735e7535fd68d3a477994ee160dfbb7d7bb7', calculated: 'ccca6fbbc20c832d004164ffdc50fa50fd19aa6360916d643a508e71dff6a219'

$ rustup -V
rustup 0.6.4 (e6dc1c6 2016-10-24)

Do you need anything else for debugging?

**Comment by Diggsey** [comment]
It's a known issue, dup of #346 - it will fix itself in time and a proper fix is in the works but is non-trivial so may take a while.
