### ISSUE TITLE
rustup doesn't install itself?

### ISSUE THREAD

**Issue by bronson** [rust-lang-nursery/rustup.rs#786]
Using rustup to install rustc worked, except that it left no rustup command to run and no clear way to install it.

```
~$ curl -sSf https://static.rust-lang.org/rustup.sh | sh
rustup: gpg not available. signatures will not be verified
rustup: downloading manifest for 'stable'
rustup: downloading toolchain for 'stable'
######################################################################## 100.0%
rustup: installing toolchain for 'stable'
rustup: extracting installer
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'rust-std-x86_64-apple-darwin'
install: installing component 'rust-docs'
install: installing component 'cargo'

    Rust is ready to roll.

```

Now rustc and cargo work great, but rustup is nowhere to be found.  It's not in /usr/local/bin or ~/.cargo/bin, and it doesn't appear installable via Cargo.

Do I need to manually download it and copy it somewhere onto my path to use it?

**Comment by Diggsey** [comment]
That's the older rustup shell script which just installs rust - you can find installation instructions for rustup on https://rustup.rs

**Comment by bronson** [comment]
I'm really glad the new rustup detects the old install and tells how to remove it.  Made it really easy to recover from this dead end.

Looking forward to when all links are updated.  Liking the beta so far.
