### ISSUE TITLE
rustup-init.sh fails with gnu coreutils because its mktemp does need a valid template

### ISSUE THREAD

**Issue by ibotty** [rust-lang-nursery/rustup.rs#791]
The following invocation of mktemp (from the script) fails.
```
> mktemp -d -t rustup
mktemp: too few X's in template ‘rustup’
```

while 
```
> mktemp -d rustup-XXXXX
```
works.

**Comment by ibotty** [comment]
sorry for the noise. It failed because of a read-only /tmp, and tried to use bsd mktemp invocation.

**Comment by shepmaster** [comment]
For others in the future (but more likely 90% for me), this occurred when I ran out of space in my Docker VM, which meant that creating the temp directory failed.
