### ISSUE TITLE
Illegal toolchains silently ignored

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang-nursery/rustup.rs#803]
If you want to build with a particular toolchain, you can pass it to the +:

cargo +stable build --release

Awesome. Unfortunately, it will happily ignore any mistyped name you give it

cargo +stablle build --release

Seems like this should be an error

(ps: I posted over at https://github.com/rust-lang/cargo/issues/3264 but Alex told me it was probably a rustup thing)

**Comment by brson** [comment]
I see an error reported:

```
brian@ip-10-145-43-250:/mnt2/dev/quandl⟫ cargo +stablle build
error: toolchain 'stablle' is not installed
```

Seems like it works as expected.
