### ISSUE TITLE
Some rustup commands never exit

### ISSUE THREAD

**Issue by wagenet** [rust-lang-nursery/rustup.rs#805]
I'm on macOS Sierra. `rustup install` is hanging. When I run it verbose, I see a message that the install happened but `rustup` never exits.

**Comment by cardoe** [comment]
Similar issue here. Experiencing an infinite hang running `rustup toolchain install 1.6.0-x86_64-apple-darwin` using rustup 0.6.5 on macOS Sierra (10.12.1). It looks like its trying to run `/Users/cardoe/.multirust/toolchains/1.6.0-x86_64-apple-darwin/bin/rustc` which itself is hanging. When I manually run it I get the following output:
```
$ /Users/cardoe/.multirust/toolchains/1.6.0-x86_64-apple-darwin/bin/rustc --version
dyld: Library not loaded: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-ca9f0d77.dylib
  Referenced from: /Users/cardoe/.multirust/toolchains/1.6.0-x86_64-apple-darwin/bin/rustc
  Reason: image not found
[1]    94724 abort      /Users/cardoe/.multirust/toolchains/1.6.0-x86_64-apple-darwin/bin/rustc
```

**Comment by cardoe** [comment]
I should note that rustup is hung with the following:
```
$ rustup toolchain install 1.6.0-x86_64-apple-darwin
info: syncing channel updates for '1.6.0-x86_64-apple-darwin'
info: downloading component 'rust'
 84.1 MiB /  84.1 MiB (100 %)   1.2 MiB/s ETA:   0 s
info: installing component 'rust'
```

Its been 35 minutes.

**Comment by cardoe** [comment]
Looks oddly similar to #729.

**Comment by wagenet** [comment]
Looks like this is indeed a duplicate of #729. I don't see this behavior for all Rust versions, only certainly slightly older ones.
