### ISSUE TITLE
stdin isn't a terminal

### ISSUE THREAD

**Issue by MarcoPolo** [rust-lang-nursery/rustup.rs#98]
Running on 64 bit os x, I get this error on running `multirust`

```
This is the currently installed multirust binary.

-n Press any key to continue...
stty: stdin isn't a terminal
error: command failed: 'shell' (Status: exit code: 1)
```

Has anyone else seen this?

**Comment by crumblingstatue** [comment]
I get a similar error on Arch Linux x86_64, when running multirust-rs from the terminal, and it shows the Press any key prompt.

```
Press any key to continue...stty: 'standard input': Inappropriate ioctl for device
error: command failed: 'shell' (Status: exit code: 1)
```

**Comment by michaelsproul** [comment]
I get the same error on Linux Mint 17.3 x86_64.

**Comment by brson** [comment]
Thanks for the report! I've got a [big patch incoming](https://github.com/rust-lang-nursery/multirust-rs/pull/106) that touches this code, so I suggest we wait until it lands and see if this persists.

**Comment by Diggsey** [comment]
Please re-open if this is still an issue
